#ifndef PROJECT_FILES_H
#define PROJECT_FILES_H

#include <stdint.h>

//==============================================================================
// Jumperless Projects - Compile-time Configuration
//==============================================================================
// This file is AUTO-GENERATED by scripts/generate_projects.py
// Do not edit manually! Edit the files in scripts/projects/<dir>/ instead.
//
// Consumed by projectFiles[] / initializeProjects() in
// src/remembering/FilesystemStuff.cpp. These are DEFINITIONS (not extern
// declarations), so exactly ONE translation unit may include this header -
// same rule as micropythonExamples.h.
//==============================================================================

// Define which projects to include at compile time
// Comment out any project you don't want provisioned
#define INCLUDE_PROJECT_555

// Convenience define to disable every project at once
// #define DISABLE_ALL_PROJECTS

#ifdef DISABLE_ALL_PROJECTS
#undef INCLUDE_PROJECT_555
#endif

//==============================================================================
// Project Files - Embedded Contents
//==============================================================================

//---------- 555 (scripts/projects/555/) ----------
#ifdef INCLUDE_PROJECT_555
const char* PROJECT_555_README_MD = R"(# 555 LED Flasher

An NE555 wired as an astable multivibrator, blinking an LED at about 1.4 Hz.
The Jumperless makes every connection between the parts; you only push the
parts into the breadboard.

## Parts you need

| Part | Value | Package | Rows |
|------|-------|---------|------|
| U1   | NE555 | DIP-8   | pin 1 at row 5, across the middle gap |
| R1   | 10k   | axial   | 12 - 13 |
| R2   | 47k   | axial   | 15 - 16 |
| C1   | 10uF  | electrolytic | + at 18, - at 19 |
| LED1 | any   | 2-lead  | anode (long leg) 22, cathode 23 |
| R3   | 330   | axial   | 25 - 26 |

Top rail is set to 5 V. ADC0 watches OUT (row 7), ADC1 watches the timing
cap (row 37).

## What it does

R1 charges C1 through R1+R2 and discharges it through R2, so

    f = 1.44 / ((R1 + 2*R2) * C1) = 1.44 / (104k * 10uF) = ~1.4 Hz

The LED blinks at that rate, slightly longer on than off (duty ~52%).
`main.py` counts the edges on OUT and prints a line every 3 seconds:

    freq: 1.38 Hz   cap: 2.91 V

and mirrors the frequency to the OLED if one is attached. Hold the
clickwheel to stop it.

## Running it

- **Clickwheel:** Apps > Projects > 555.
- **Files browser:** open `/projects/555/wiring.yaml` to load the circuit,
  then run `/projects/555/main.py`.

## Troubleshooting

- No blink at all: check the 555's orientation - pin 1 (next to the dot) at
  row 5, and the chip must straddle the middle gap.
- Blinking way too fast or slow: R1/R2 swapped, or the cap is not 10uF.
- LED dark but OUT reads ~2.5 V average: the LED is backwards. Long leg goes
  in row 22.
)";
const uint32_t PROJECT_555_README_MD_HASHES[1] = { 0x4E203A59 };
const int PROJECT_555_README_MD_HASH_COUNT = 1;

const char* PROJECT_555_MAIN_PY = R"("""555 LED Flasher - companion script for /projects/555/wiring.yaml

Watches the 555's OUT pin (bridged to ADC0 by the wiring file), counts the
rising edges past a 2.5 V threshold, and reports the blink rate every 3
seconds along with the timing cap's voltage (ADC1 -> node 37).

Runs standalone from the Files browser too - the launcher injects
_jl_project, but nothing here depends on it.
"""

import time

# The launcher injects this global; default so the script also runs standalone.
_jl_project = globals().get("_jl_project", {})

THRESHOLD = 2.5     # volts - the 555's OUT swings rail to rail
REPORT_MS = 3000    # print a line this often

print("555 astable running...")
print("Hold the clickwheel to exit.")
if _jl_project:
    print("project: " + str(_jl_project.get("dir", "555")) +
          "  variant: " + str(_jl_project.get("variant", "default")))

try:
    oled_connect()
except Exception:
    pass

edges = 0
above = adc_get(0) > THRESHOLD
window_start = time.ticks_ms()

try:
    while True:
        out_v = adc_get(0)
        if out_v > THRESHOLD:
            if not above:
                edges += 1     # rising edge
                above = True
        elif out_v < THRESHOLD:
            above = False

        elapsed = time.ticks_diff(time.ticks_ms(), window_start)
        if elapsed >= REPORT_MS:
            freq = (edges * 1000.0) / elapsed
            cap_v = adc_get(1)
            print("freq: %.2f Hz   cap: %.2f V" % (freq, cap_v))
            try:
                oled_print("%.2f Hz" % freq)
            except Exception:
                pass
            edges = 0
            window_start = time.ticks_ms()

        time.sleep(0.002)   # ~500 Hz sampling: plenty for a ~1.4 Hz blink

except KeyboardInterrupt:
    try:
        oled_clear()
    except Exception:
        pass
    print("bye")
)";
const uint32_t PROJECT_555_MAIN_PY_HASHES[1] = { 0xD488958C };
const int PROJECT_555_MAIN_PY_HASH_COUNT = 1;

const char* PROJECT_555_WIRING_YAML = R"===(version: 2
sourceOfTruth: bridges
meta:
  project: 555
  title: "555 LED Flasher"
  variant: default
  summary: "NE555 astable blinking an LED at ~1.4 Hz"
  script: main.py
  needs: ["NE555 (DIP-8)", "10k", "47k", "10uF cap", "LED", "330"]
parts:
  - name: "U1"
    type: ic
    value: "NE555"
    footprint: dip8
    row: 5
    pins:
      GND:   {pin: 1, connect: GND,      class: gnd}
      TRIG:  {pin: 2, connect: 37,       class: signal}
      OUT:   {pin: 3,                    class: signal}
      RESET: {pin: 4, connect: TOP_RAIL, class: power}
      CTRL:  {pin: 5,                    class: nc}
      THR:   {pin: 6,                    class: signal}
      DIS:   {pin: 7,                    class: signal}
      VCC:   {pin: 8, connect: TOP_RAIL, class: power}
  - name: "R1"
    type: resistor
    value: "10k"
    footprint: sip2
    row: 12
    pins: {A: {pin: 1, connect: TOP_RAIL}, B: {pin: 2, connect: 36}}
  - name: "R2"
    type: resistor
    value: "47k"
    footprint: sip2
    row: 15
    pins: {A: {pin: 1, connect: 36}, B: {pin: 2, connect: 37}}
  - name: "C1"
    type: capacitor
    value: "10uF"
    footprint: sip2
    row: 18
    pins: {PLUS: {pin: 1, connect: 37}, MINUS: {pin: 2, connect: GND}}
  - name: "LED1"
    type: led
    footprint: sip2
    row: 22
    pins: {A: {pin: 1}, K: {pin: 2, connect: GND}}
  - name: "R3"
    type: resistor
    value: "330"
    footprint: sip2
    row: 25
    pins: {A: {pin: 1, connect: 7}, B: {pin: 2, connect: 22}}
guide:
  title: "555 LED Flasher"
  steps:
    - {do: note, text: "A 555 blinker. Wheel: turn=prev/next, click=confirm, hold=exit."}
    - {do: place, part: U1, check: presence, on_fail: warn, text: "555 across the middle gap, pin 1 (the dot) at row 5."}
    - {do: place, part: R1, check: continuity, min: 0.1, max: 0.8, text: "10k resistor: rows 12 and 13."}
    - {do: place, part: R2, check: continuity, min: 0.04, max: 0.3, text: "47k resistor: rows 15 and 16."}
    - {do: place, part: C1, check: presence, text: "10uF cap: + (long leg) row 18, - row 19."}
    - {do: place, part: LED1, check: vf, min: 1.4, max: 2.6, on_fail: retry, text: "LED: long leg (anode) row 22, short leg row 23."}
    - {do: place, part: R3, check: continuity, min: 5.0, max: 15.0, text: "330 resistor: rows 25 and 26."}
    - {do: power_on, check: rail_sane, text: "Confirm to power up (5V)."}
    - {do: verify, target: 7, check: oscillates, min: 0.3, max: 30, text: "The LED should be blinking (~1.4 Hz). Checking OUT..."}
bridges:
  - {n1: ADC0, n2: 7}
  - {n1: ADC1, n2: 37}
nets:
  - {num: 7, name: "TIMING", color: 0xff8800, nodes: [37], user: true}
power:
  topRail: 5.0
)===";
const uint32_t PROJECT_555_WIRING_YAML_HASHES[1] = { 0xC8CBC62E };
const int PROJECT_555_WIRING_YAML_HASH_COUNT = 1;

#endif // INCLUDE_PROJECT_555

//==============================================================================
// FilesystemStuff.cpp Integration Guide
//==============================================================================
// Copy the following entries into the projectFiles[] array in
// src/remembering/FilesystemStuff.cpp (used by initializeProjects()).
// ProjectFileInfo struct: { path, content, name, knownHashes, hashCount }
//
// initializeProjects() creates the parent directories of each path on
// demand, so a new project needs no directory list anywhere.
//
// #ifdef INCLUDE_PROJECT_555
//         { "/projects/555/README.md", PROJECT_555_README_MD, "555/README.md", PROJECT_555_README_MD_HASHES, PROJECT_555_README_MD_HASH_COUNT },
//         { "/projects/555/main.py", PROJECT_555_MAIN_PY, "555/main.py", PROJECT_555_MAIN_PY_HASHES, PROJECT_555_MAIN_PY_HASH_COUNT },
//         { "/projects/555/wiring.yaml", PROJECT_555_WIRING_YAML, "555/wiring.yaml", PROJECT_555_WIRING_YAML_HASHES, PROJECT_555_WIRING_YAML_HASH_COUNT },
// #endif
//

#endif // PROJECT_FILES_H