#ifndef PROJECT_FILES_H
#define PROJECT_FILES_H

#include <stdint.h>

//==============================================================================
// Jumperless Projects - Compile-time Configuration
//==============================================================================
// This file is AUTO-GENERATED by scripts/generate_projects.py
// Do not edit manually! Edit the files in scripts/projects/<dir>/ instead.
//
// Consumed by projectFiles[] / initializeProjects() in
// src/remembering/FilesystemStuff.cpp. These are DEFINITIONS (not extern
// declarations), so exactly ONE translation unit may include this header -
// same rule as micropythonExamples.h.
//==============================================================================

// Define which projects to include at compile time
// Comment out any project you don't want provisioned
#define INCLUDE_PROJECT_555
#define INCLUDE_PROJECT_EEPROM
#define INCLUDE_PROJECT_I2CSCRN
#define INCLUDE_PROJECT_NAND00

// Convenience define to disable every project at once
// #define DISABLE_ALL_PROJECTS

#ifdef DISABLE_ALL_PROJECTS
#undef INCLUDE_PROJECT_555
#undef INCLUDE_PROJECT_EEPROM
#undef INCLUDE_PROJECT_I2CSCRN
#undef INCLUDE_PROJECT_NAND00
#endif

//==============================================================================
// Project Files - Embedded Contents
//==============================================================================

//---------- 555 (scripts/projects/555/) ----------
#ifdef INCLUDE_PROJECT_555
const char* PROJECT_555_README_MD = R"(# 555 LED Flasher

An NE555 wired as an astable multivibrator, blinking an LED. The Jumperless
makes every connection between the parts; you only push the parts into the
breadboard.

## Parts you need

**The values below are what is in the drawer, not what the project requires.**
Nothing in the guide fails you for using something else: each resistor step
measures what you put in and reports it, and `main.py` works out the blink rate
*your* parts should give. Bring roughly the right order of magnitude and the
project tells you what you built.

| Part | Suggested | Package | Rows | Anything from |
|------|-----------|---------|------|---------------|
| U1   | NE555 | DIP-8   | pin 1 at row 35, across the middle gap | - |
| R1   | 10k   | axial   | 10 - 40, straddling the middle gap | 1k - 100k |
| R2   | 47k   | axial   | 13 - 43, straddling the middle gap | 1k - 100k |
| C1   | 10uF  | electrolytic | + at 18, - at 19 | 1uF - 100uF |
| LED1 | any   | 2-lead  | anode (long leg) 22, cathode 23 | any colour |
| R3   | 330   | axial   | 16 - 46, straddling the middle gap | 100R - 2k |

The steps still fail on the two things that are mistakes rather than choices:
a resistor reading **open** (a leg not seated in the hole) or **short** (both
legs the same side of the ravine), and an LED drawing **no current**, which is
what a backwards LED looks like electrically.

Top rail is set to 5 V. Nothing else is pre-wired: opening the project leaves
the breadboard completely bare, and every connection appears as you confirm
each part in the guide.

`main.py` needs two measurement taps - **ADC0 on row 37 (OUT)** and **ADC1 on
row 7 (the timing cap)** - so *it* makes them when it starts and removes them
when it exits. They used to ship in the wiring file, which put two wires on the
board before you had placed a single part. If you had already tapped one of
those rows yourself, the script notices and leaves your connection alone.

## What it does

C1 charges through R1+R2 and discharges through R2, so

    f    = 1.44 / ((R1 + 2*R2) * C1)
    duty = (R1 + R2) / (R1 + 2*R2)

With the suggested parts that is 1.44 / (104k * 10uF) = **~1.4 Hz** at a
**~55%** duty cycle - slightly longer on than off, because the charge path is
the longer one.

`main.py` does not assume any of that. It asks the board what is actually
placed, via `list_parts()`:

- **R1, R2** come back with a `measured` field - the ohms the guide's
  continuity check really read across that resistor, four-wire, during the
  build. That is the number the prediction uses.
- **C1** has no `measured` field, because capacitance is not something this
  hardware can measure. Its `value:` is taken on trust, and the script says so.

Then it counts rising edges on OUT and the fraction of samples above 2.5 V, and
prints both sides every 3 seconds:

    your parts: R1 9.83k  R2 47.2k  C1 10uF   (R measured)
    they predict: 1.41 Hz, 55% high
    measured: 1.33 Hz, 54% high   (predicted 1.41 Hz, 55%)   cap 2.91 V
      the blink implies C1 = 10.6uF

That last line solves the equation backwards for the one component nothing can
measure. If it lands far from the value on your capacitor, the capacitor is the
part that is not what the file thinks it is - electrolytics of this size are
routinely -20/+80% and this is how you see yours. Counting whole edges in a 3 s
window puts the measured frequency on a 1/3 Hz grid, so treat ±0.33 Hz as the
resolution, not as disagreement.

The frequency is mirrored to the OLED if one is attached. Hold the clickwheel
to stop it.

If you run `main.py` straight from the Files browser rather than after a guided
build, there are no measurements to read - `measured` is RAM-only and does not
survive a reboot - so it falls back to the file's values and tells you it did.

## Running it

- **Clickwheel:** `Guides` - it is a top-level menu row, before `Apps` - then
  **555**, and walk the guided build. That is what wires the parts up. Run
  `main.py` when it offers at the end.
- **Headless:** `z 555` on the terminal drives the same flow. Add `new` to
  start over from the wiring, `load` to reopen the run you already have,
  `noscript` to stop at the wiring.

Launching a project does not borrow a slot any more. It opens
`/projects/555/555_run.yaml` - a **run file** - and makes it your active
circuit, exactly as if you had clicked a YAML in the Files browser. There is
**one run file per project** and it is reused: your build is saved into it at
every step, the board comes back to it after a power cycle, and the next launch
reopens it silently - unless you quit a guided build part way through, in which
case you are asked once whether to resume or to start over. To keep a run,
`slots` > `save to` while it is active. The shipped `wiring.yaml` is a
read-only template and is never written to.

Clicking `wiring.yaml` in the Files browser starts a run the same way. Either
route, **only a guide commit wires a part**: `expandPartsToBridges()` skips any
part still marked `placed: false`. This project has no `bridges:` section at
all, so a run you have not walked through yet has **nothing** on the
breadboard.

## Moving parts around

**Compact vs expanded.** Every two-leg part can sit two ways. **Expanded** puts
it at its own rows and the Jumperless routes its connections through the
crossbar underneath - good while you are building, because each part is easy to
see and to test on its own. **Compact** is how you would breadboard it by hand:
the legs go straight into the rows they connect to - a resistor from a chip's
pin row to the rail goes leg-in-row-7, leg-in-the-rail - and the routed
connections for that part disappear, because the legs themselves make the
contact.

Tap a part's lit footprint with the probe to flip that one part between the
two. **Every part remembers its own setting.** A leg whose endpoint is not a
real hole - `GND` and the analog pins live in the crossbar, not on the board -
keeps its own row and its routed connection either way, so a compact part can
still have one bridge.

To **move** a part, tap any free hole and pin 1 jumps there. The wheel never
moves a part - it only browses the steps. On the terminal, `m <row>` and `c` do
the same two things the probe does. Chips (DIPs) anchor at pin 1 - the dot or
the notch - wherever it really sits: **bottom-left** (rows 31-60) or rotated
180 with pin 1 top-right (rows 1-30). Axial parts (resistors, diodes) straddle the
middle gap by default; radial parts (caps, LEDs) sit in two neighbouring rows.

**Browsing.** The wheel moves *between* steps rather than confirming them, and
the ring wraps: turn past the last step and you land on a summary of what is
built, skipped and still outstanding; turn again and you are back at step 1. A
turn never ends the build - hold the wheel, or press `q`, for that. You can skip
a part with `s` and come back to it later, and confirming at the summary jumps
you to the first thing you have not built yet.

> Measuring and *identifying* an unknown part (`identify_part(leftmost_row=...)`)
> is planned but is not in this release. What the guide shows today is the value
> each verify step measures - a resistance, a diode drop, a rail voltage.

## Troubleshooting

- No blink at all: check the 555's orientation - pin 1 (next to the dot) at
  row 35, and the chip must straddle the middle gap.
- Blinking at a rate you did not expect: read the script's own two lines before
  suspecting a fault. If `measured` and `predicted` agree, the circuit is
  working correctly and the parts are simply not the ones the file suggests. If
  they disagree and `the blink implies C1 = ...` is far from your cap's marking,
  believe the implied value.
- A resistor step says **open**: a leg is not in the hole, or it is in the wrong
  row. It is not complaining about the value - no value is enforced.
- LED dark but OUT reads ~2.5 V average: the LED is backwards. Long leg goes
  in row 22.
)";
const uint32_t PROJECT_555_README_MD_HASHES[10] = { 0x9DD76F48, 0x6B944773, 0x043F6084, 0x0F3158A4, 0x72FF45E0, 0x561E244A, 0x7F9D3D88, 0xE846A64A, 0x52517D68, 0x4E203A59 };
const int PROJECT_555_README_MD_HASH_COUNT = 10;

const char* PROJECT_555_MAIN_PY = R"===("""555 LED Flasher - companion for /projects/555/wiring.yaml. See README.md.

Times the blink on OUT and compares it to what the parts actually placed
predict - resistors come back from list_parts()['measured'], so substituting
one moves the answer instead of breaking anything.

  ADC0 -> row 37   OUT (U1 pin 3, dip8 anchored at row 35)
  ADC1 -> row 7    the RC junction - THR/TRIG and C1's + leg

Both taps are made here and removed on the way out, and only the ones this run
created. Runs standalone from the Files browser; _jl_project is optional.

KEEP THIS LEAN - MicroPython compiles it out of one shared heap that never
resets between runs, so every KB here is a KB the next script cannot have.
"""

import time

_jl_project = globals().get("_jl_project", {})

THRESHOLD = 2.5     # volts - OUT swings rail to rail
REPORT_MS = 3000

OUT_ROW = 37
CAP_ROW = 7
TAPS = (("ADC0", OUT_ROW), ("ADC1", CAP_ROW))

_MUL = {"p": 1e-12, "n": 1e-9, "u": 1e-6, "m": 1e-3,
        "": 1.0, "k": 1e3, "K": 1e3, "M": 1e6}


def val(s):
    """'47k'->47000.0, '10uF'->1e-05, '330'->330.0, else 0.0. '4k7' reads as
    4k - close enough, and the guide measures resistors anyway."""
    s = (s or "").strip()
    n = ""
    i = 0
    while i < len(s) and (s[i].isdigit() or s[i] in ".+-"):
        n += s[i]
        i += 1
    if not n:
        return 0.0
    try:
        return float(n) * _MUL.get(s[i:i + 1], 1.0)
    except Exception:
        return 0.0


def eng(x):
    for m, suf in ((1e6, "M"), (1e3, "k"), (1, ""),
                   (1e-3, "m"), (1e-6, "u"), (1e-9, "n")):
        if abs(x) >= m:
            return "%.3g%s" % (x / m, suf)
    return "%.3g" % x


made = []


def taps_up():
    for node, row in TAPS:
        try:
            if is_connected(node, row):
                print("tap %s-%d was already there - left alone" % (node, row))
                continue
            connect(node, row)
            made.append((node, row))
        except Exception as e:
            print("could not tap %s-%d: %s" % (node, row, str(e)))


def taps_down():
    while made:
        node, row = made.pop()
        try:
            disconnect(node, row)
        except Exception as e:
            print("could not un-tap %s-%d: %s" % (node, row, str(e)))


def expected():
    """(f_Hz, duty_pct, R1, R2, C1, how) from the parts on the board.

    A resistor's `measured` ohms beats the file's `value:`. C1 has no such
    reading - capacitance is not measurable here - so it is taken on trust.
    """
    p = {}
    try:
        for e in list_parts():
            p[e["name"]] = e
    except Exception:
        pass

    real = 0

    def ohms(name):
        e = p.get(name)
        if not e:
            return 0.0
        m = e.get("measured", 0.0)
        if m and m > 0:
            return m
        return val(e.get("value", ""))

    for n in ("R1", "R2"):
        e = p.get(n)
        if e and e.get("measured", 0.0) > 0:
            real += 1
    r1, r2 = ohms("R1"), ohms("R2")
    c1 = val(p.get("C1", {}).get("value", ""))
    how = ("measured" if real == 2 else
           "part-measured" if real else "from the project file")
    if r1 > 0 and r2 > 0 and c1 > 0:
        span = r1 + 2 * r2
        return 1.44 / (span * c1), 100.0 * (r1 + r2) / span, r1, r2, c1, how
    return 0.0, 0.0, r1, r2, c1, how


print("555 astable")
print("Hold the clickwheel to exit.")
if _jl_project:
    print("project: " + str(_jl_project.get("dir", "555")))

# Everything from taps_up() on is inside the try, so `finally` owns the taps
# from the instant they exist - a Ctrl-C during set-up must not strand them.
try:
    taps_up()

    exp_f, exp_d, R1, R2, C1, how = expected()
    if exp_f > 0:
        print("your parts: R1 %s  R2 %s  C1 %sF   (R %s)"
              % (eng(R1), eng(R2), eng(C1), how))
        print("they predict: %.2f Hz, %.0f%% high" % (exp_f, exp_d))
        if how != "measured":
            print("  (no continuity reading for every resistor - run the")
            print("   guided build to measure them instead of trusting the file)")
    else:
        print("no usable R1/R2/C1 values - reporting the measurement only")

    try:
        oled_connect()
    except Exception:
        pass

    edges = 0
    high = 0
    total = 0
    above = adc_get(0) > THRESHOLD
    window_start = time.ticks_ms()

    while True:
        out_v = adc_get(0)
        total += 1
        if out_v > THRESHOLD:
            high += 1
            if not above:
                edges += 1     # rising edge
                above = True
        else:
            above = False

        elapsed = time.ticks_diff(time.ticks_ms(), window_start)
        if elapsed >= REPORT_MS:
            freq = (edges * 1000.0) / elapsed
            duty = (100.0 * high / total) if total else 0.0
            line = "%.2f Hz, %.0f%% high" % (freq, duty)
            if exp_f > 0:
                # Side by side, never pass/fail - the bench decides.
                line += "   (predicted %.2f Hz, %.0f%%)" % (exp_f, exp_d)
            print("measured: %s   cap %.2f V" % (line, adc_get(1)))
            if freq > 0.05 and R1 > 0 and R2 > 0:
                # The unmeasurable part, solved backwards from the blink.
                print("  the blink implies C1 = %sF" % eng(1.44 / ((R1 + 2 * R2) * freq)))
            try:
                oled_print("%.2f Hz" % freq)
            except Exception:
                pass
            edges = high = total = 0
            window_start = time.ticks_ms()

        time.sleep(0.002)   # ~500 Hz: plenty for a ~1 Hz blink, and it is what
                            # makes the duty-cycle count meaningful

except KeyboardInterrupt:
    pass
finally:
    # finally, not just the except arm: a break, an exception and a clean
    # fall-through all have to leave the board the way we found it.
    taps_down()
    try:
        oled_clear()
    except Exception:
        pass
    print("bye")
)===";
const uint32_t PROJECT_555_MAIN_PY_HASHES[6] = { 0x7B1AEC22, 0x228EBF07, 0x2BE6A1DA, 0xFD94A80B, 0x89075267, 0xD488958C };
const int PROJECT_555_MAIN_PY_HASH_COUNT = 6;

const char* PROJECT_555_WIRING_YAML = R"===(version: 2
sourceOfTruth: bridges
meta:
  project: 555
  title: "555 LED Flasher"
  variant: default
  summary: "NE555 astable blinking an LED - your R and C set the rate"
  script: main.py
  needs: ["NE555 (DIP-8)", "~10k", "~47k", "~10uF cap", "LED", "~330"]
parts:
  - name: "U1"
    type: ic
    value: "NE555"
    footprint: dip8
    row: 35
    pins:
      GND:   {pin: 1, connect: GND,      class: gnd}
      TRIG:  {pin: 2, connect: 7,        class: signal}
      OUT:   {pin: 3,                    class: signal}
      RESET: {pin: 4, connect: TOP_RAIL, class: power}
      CTRL:  {pin: 5,                    class: nc}
      THR:   {pin: 6,                    class: signal}
      DIS:   {pin: 7,                    class: signal}
      VCC:   {pin: 8, connect: TOP_RAIL, class: power}
  - name: "R1"
    type: resistor
    value: "10k"
    footprint: axial2
    row: 10
    pins: {A: {pin: 1, connect: TOP_RAIL}, B: {pin: 2, connect: 6}}
  - name: "R2"
    type: resistor
    value: "47k"
    footprint: axial2
    row: 13
    pins: {A: {pin: 1, connect: 6}, B: {pin: 2, connect: 7}}
  - name: "C1"
    type: capacitor
    value: "10uF"
    footprint: sip2
    row: 18
    pins: {PLUS: {pin: 1, connect: 7}, MINUS: {pin: 2, connect: GND}}
  - name: "LED1"
    type: led
    footprint: sip2
    row: 22
    pins: {A: {pin: 1}, K: {pin: 2, connect: GND}}
  - name: "R3"
    type: resistor
    value: "330"
    footprint: axial2
    row: 16
    pins: {A: {pin: 1, connect: 37}, B: {pin: 2, connect: 22}}
guide:
  title: "555 LED Flasher"
  # NOTHING HERE JUDGES A COMPONENT VALUE. Every `value:` above is a suggestion
  # for the parts bin, not a requirement: `enforce: false` on the R steps means
  # the check measures the resistor, reports what it read, and passes. The two
  # verdicts that still fail are the ones that are PLACEMENT mistakes rather
  # than value mistakes - open (a leg not seated) and short (both legs the same
  # side of the ravine) - plus "no current" on the LED, which is what a
  # backwards LED looks like from here.
  #
  # Whatever the user actually reached for is then the truth the companion
  # script computes from: every measured resistance lands in that part's
  # `measured` field, main.py reads it back through list_parts(), and prints
  # the frequency and duty cycle THOSE parts predict next to the ones the board
  # observes. Substituting a 22k for the 47k changes the answer instead of
  # failing the build, which is the whole point of a starter project.
  steps:
    - {do: note, text: "A 555 blinker - any R and C work, the script does the math. Turn, click, hold=exit."}
    - {do: place, part: U1, check: presence, on_fail: warn, text: "555 across the middle gap, pin 1 (the dot) at row 35."}
    - {do: place, part: R1, check: continuity, enforce: false, text: "10k-ish: rows 10 and 40, over the gap. Anything 1k-100k works - it gets measured."}
    - {do: place, part: R2, check: continuity, enforce: false, text: "47k-ish: rows 13 and 43, over the gap. Larger than R1 gives a more even blink."}
    - {do: place, part: C1, check: presence, text: "10uF cap: + (long leg) row 18, - row 19. A different value is fine."}
    - {do: place, part: LED1, check: vf, enforce: false, on_fail: retry, text: "LED: long leg (anode) row 22, short leg row 23. Any colour."}
    - {do: place, part: R3, check: continuity, enforce: false, text: "330-ish for the LED: rows 16 and 46, over the gap. 100R to 2k all fine."}
    - {do: power_on, check: rail_sane, text: "Confirm to power up (5V)."}
    # No `check: oscillates` here. It drives a 3.3 V GPIO onto the target and
    # refuses a node that can swing to this project's 5 V rail, so on the
    # shipped wiring it can only ever report `unmeasured` - a step that cannot
    # succeed is worse than no step. The blink rate is measured properly by
    # main.py, off ADC0, where it can also be compared against the parts.
    - {do: note, text: "Built. Run main.py - it times the blink and checks it against your parts."}
# NO bridges: and no nets: on purpose. Opening this project must leave the
# breadboard completely unconnected - every connection here belongs to a part
# and waits for the guide to commit it. The two ADC taps that used to live here
# (ADC0-37 on OUT, ADC1-7 on the timing cap) showed up as two wires nobody
# asked for the moment the project opened; main.py makes them itself now, and
# takes them back down when it exits. The `nets:` entry that named node 7
# "TIMING" went with them - it could only ever attach because the ADC1 tap put
# node 7 in a net at load time.
power:
  topRail: 5.0
)===";
const uint32_t PROJECT_555_WIRING_YAML_HASHES[5] = { 0x8158E30E, 0x8E29492C, 0xEEC03F56, 0x2E55BF41, 0xC8CBC62E };
const int PROJECT_555_WIRING_YAML_HASH_COUNT = 5;

#endif // INCLUDE_PROJECT_555

//---------- eeprom (scripts/projects/eeprom/) ----------
#ifdef INCLUDE_PROJECT_EEPROM
const char* PROJECT_EEPROM_README_MD = R"(# EEPROM Dumper

A 24Cxx serial EEPROM in the breadboard, read over I2C and hex-dumped to the
terminal. The Jumperless makes every connection - including the one that
decides whether the chip can be written at all.

## Parts you need

| Part | Value | Package | Rows |
|------|-------|---------|------|
| U1   | 24C02 (or 24C16) | DIP-8 | pin 1 at row 35, across the middle gap |
| R1   | 4.7k  | axial   | 12 - 42, straddling the middle gap (SDA pull-up) |
| R2   | 4.7k  | axial   | 15 - 45, straddling the middle gap (SCL pull-up) |

Top rail is set to 3.3 V.

The 24Cxx pinout, and where each pin lands with pin 1 at row 35:

| Pin | Name | Row | Goes to |
|---|---|---|---|
| 1 | A0  | 35 | GND |
| 2 | A1  | 36 | GND |
| 3 | A2  | 37 | GND |
| 4 | GND | 38 | GND |
| 5 | SDA | 8  | `RP_GPIO_7` (RP pin 26) |
| 6 | SCL | 7  | `RP_GPIO_8` (RP pin 27) |
| 7 | WP  | 6  | top rail - **write protected** |
| 8 | VCC | 5  | top rail |

A0-A2 all grounded puts the chip at **0x50**.

> **Jumperless V5 only.** This project routes breadboard rows to
> `RP_GPIO_7` and `RP_GPIO_8`, and those nodes exist only on the V5. The original
> Jumperless has exactly three routable GPIO (`RP_GPIO_0` plus UART
> TX/RX), so the wiring loads there but cannot be routed.

### Why the two resistors are not optional

I2C is an open-drain bus: the chips only ever pull the lines *down*, so
something has to pull them back up. A 4-pin display module has pull-ups
soldered on it; a bare DIP EEPROM does not. The RP2350's internal pull-ups
are around 50-80k, and 60k into the crossbar-plus-breadboard capacitance
gives a rise time of a couple of microseconds - well past the 1 us the
100 kHz I2C spec allows. 4.7k brings that down to well under 500 ns.

### Write protect is a wire, not a jumper

Pin 7 (WP) high means "reads only". The wiring holds row 6 at the top
rail, so the chip is genuinely read-only from the moment it powers up -
not read-only by convention.

The optional write test in `main.py` is the only thing that changes that,
and it does so by re-routing, not by asking you to move a jumper:

    disconnect(6, TOP_RAIL)
    connect(6, GND)            # writes enabled for exactly one byte
    ...
    disconnect(6, GND)
    connect(6, TOP_RAIL)       # in a finally, so it always goes back

That re-route runs `refreshConnections()`, which re-asserts the slot's GPIO
configuration onto RP pins 26/27 - so the script rebuilds its `machine.I2C`
object afterwards. If you ever see the restore step report a failure,
re-load the wiring before trusting the chip again.

## What it does

    EEPROM Dumper eeprom
    i2c devices: ['0x50']
    0000  FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF  |................|
    ...
    00F0  FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF  |................|
    256 bytes read.  (all 0xFF - an erased chip)
    dump more - total size in bytes (blank = no):

16 bytes to a line with a printable-ASCII gutter, the same shape `hexdump -C`
uses. Then it offers to read further (for a 24C16, answer `2048`), and last
of all offers the write test, which defaults to **no**.

`ADDR_BITS = 8` at the top of `main.py` covers the 24C01 through 24C16. A
24C32 or larger uses a 16-bit word address - set it to 16 for those.

## Running it

- **Clickwheel:** `Guides` - it is a top-level menu row, before `Apps` - then
  **eeprom**, and walk the guided build. That is what wires the parts up. Run
  `main.py` when it offers at the end.
- **Headless:** `z eeprom` on the terminal drives the same flow. Add `new` to
  start over from the wiring, `load` to reopen the run you already have,
  `noscript` to stop at the wiring.

Launching a project does not borrow a slot any more. It opens
`/projects/eeprom/eeprom_run.yaml` - a **run file** - and makes it your active
circuit, exactly as if you had clicked a YAML in the Files browser. There is
**one run file per project** and it is reused: your build is saved into it at
every step, the board comes back to it after a power cycle, and the next launch
reopens it silently - unless you quit a guided build part way through, in which
case you are asked once whether to resume or to start over. To keep a run,
`slots` > `save to` while it is active. The shipped `wiring.yaml` is a
read-only template and is never written to.

Clicking `wiring.yaml` in the Files browser starts a run the same way. Either
route, **only a guide commit wires a part**: `expandPartsToBridges()` skips any
part still marked `placed: false`. This project has no `bridges:` section at
all, so a run you have not walked through yet has **nothing** on the
breadboard.

## Moving parts around

**Compact vs expanded.** Every two-leg part can sit two ways. **Expanded** puts
it at its own rows and the Jumperless routes its connections through the
crossbar underneath - good while you are building, because each part is easy to
see and to test on its own. **Compact** is how you would breadboard it by hand:
the legs go straight into the rows they connect to - a resistor from a chip's
pin row to the rail goes leg-in-row-7, leg-in-the-rail - and the routed
connections for that part disappear, because the legs themselves make the
contact.

Tap a part's lit footprint with the probe to flip that one part between the
two. **Every part remembers its own setting.** A leg whose endpoint is not a
real hole - `GND` and the analog pins live in the crossbar, not on the board -
keeps its own row and its routed connection either way, so a compact part can
still have one bridge.

To **move** a part, tap any free hole and pin 1 jumps there. The wheel never
moves a part - it only browses the steps. On the terminal, `m <row>` and `c` do
the same two things the probe does. Chips (DIPs) sit with pin 1 - the dot or
the notch - wherever it really sits: **bottom-left** (rows 31-60) or rotated
180 with pin 1 top-right (rows 1-30). Axial parts (resistors, diodes) straddle the
middle gap by default; radial parts (caps, LEDs) sit in two neighbouring rows.

**Browsing.** The wheel moves *between* steps rather than confirming them, and
the ring wraps: turn past the last step and you land on a summary of what is
built, skipped and still outstanding; turn again and you are back at step 1. A
turn never ends the build - hold the wheel, or press `q`, for that. You can skip
a part with `s` and come back to it later, and confirming at the summary jumps
you to the first thing you have not built yet.

> Measuring and *identifying* an unknown part (`identify_part(leftmost_row=...)`)
> is planned but is not in this release. What the guide shows today is the value
> each verify step measures - a resistance, a diode drop, a rail voltage.

## Troubleshooting

- **`i2c devices: []`** - nothing acked. Most often the chip is in
  backwards: pin 1 is the end with the dot, at row 35, and the chip must
  straddle the middle gap. After that, check that both 4.7k resistors are
  really straddling the gap at rows 12/42 and 15/45.
- **A device answers, but not at 0x50** - one of A0/A1/A2 is not reaching
  GND, which shifts the address. 0x51 means A0 is high, 0x52 means A1, and
  so on. Change `ADDR` in `main.py` to match, or re-seat the chip.
- **The dump repeats every 256 bytes** - that is a 24C02, which really is
  256 bytes; the address wraps.
- **Reads work but the write test says the byte did not stick** - WP did not
  reach GND. Watch the terminal for the restore line; if the re-route
  failed, the chip stayed protected, which is the safe way to fail.
- **The Jumperless's own top OLED misbehaves while this runs** - in its
  default `connection_type 0` it lives on GPIO 7/8, the same pins, and it
  shares the i2c1 peripheral in every mode. Turn it off while you use this
  project.
)";
const uint32_t PROJECT_EEPROM_README_MD_HASHES[10] = { 0xA462E439, 0xF79BAFCE, 0x60313AF8, 0x8CCB4F44, 0x69A73992, 0x97332DFC, 0xAF82DCE7, 0x965FF7AE, 0x35314190, 0xF2E7D49B };
const int PROJECT_EEPROM_README_MD_HASH_COUNT = 10;

const char* PROJECT_EEPROM_MAIN_PY = R"===("""EEPROM Dumper - companion for /projects/eeprom/wiring.yaml.

SDA row -> RP_GPIO_7 (RP pin 26), SCL row -> RP_GPIO_8 (RP pin 27), so
machine.I2C(1) reaches the chip. WP (row 6) sits on the top rail, so the
chip is read-only until the write test re-routes that row. See README.md.
"""

import time

_jl_project = globals().get("_jl_project", {})

SDA_PIN = 26        # node RP_GPIO_7 - the wiring routes row 8 here
SCL_PIN = 27        # node RP_GPIO_8 - the wiring routes row 7 here
I2C_BUS = 1         # 26/27 are i2c1; machine.I2C(0, ...) rejects them
I2C_HZ = 100000
ADDR = 0x50         # A0/A1/A2 grounded by the wiring
ADDR_BITS = 8       # 24C01..24C16; 24C32 and larger need 16
WP_ROW = 6          # 24Cxx pin 7 = write protect, held high
FIRST = 256         # bytes in the opening dump
TEST_AT = 0xFF      # the one address the write test touches


def open_bus():
    """An I2C object, or None with an explanation printed."""
    try:
        import machine
    except Exception as e:
        print("no machine module: " + str(e))
        return None
    # Claim the pins, or every refreshConnections() re-asserts the slot
    # config's pulls onto GPIO 26/27 underneath the I2C peripheral.
    for n in (GPIO_7, GPIO_8):
        try:
            gpio_claim_pin(n)
        except Exception:
            pass
    try:
        return machine.I2C(I2C_BUS, scl=SCL_PIN, sda=SDA_PIN, freq=I2C_HZ)
    except Exception as e:
        print("no I2C on %d/%d: %s" % (SDA_PIN, SCL_PIN, str(e)))
        return None


def release_bus():
    """Give the two pins back. Called on EVERY exit from main(), including
    the one where open_bus() claimed them and then failed to build the I2C
    object - that path used to return past the finally and leak the claim."""
    for n in (GPIO_7, GPIO_8):
        try:
            gpio_release_pin(n)
        except Exception:
            pass


def hexdump(data, base=0):
    for off in range(0, len(data), 16):
        c = data[off:off + 16]
        print("%04X  %-47s  |%s|"
              % (base + off, " ".join("%02X" % b for b in c),
                 "".join(chr(b) if 32 <= b < 127 else "." for b in c)))


def read_block(i2c, start, count):
    """Sequential read, 32 bytes at a time to keep buffers small."""
    out = bytearray()
    while count > 0:
        n = 32 if count > 32 else count
        out += i2c.readfrom_mem(ADDR, start, n, addrsize=ADDR_BITS)
        start += n
        count -= n
    return out


def ask(p):
    try:
        return input(p).strip()
    except EOFError:
        return ""


def write_test(i2c, original):
    """One byte written, read back, put back. Returns the live bus."""
    probe = 0xA5 if original != 0xA5 else 0x5A
    moved = False
    try:
        disconnect(WP_ROW, TOP_RAIL)
        # Never add GND while the rail is still on that row: the two together
        # are a short across the supply, through the crossbar. If the
        # disconnect did not take, stop here - protected is the safe way out.
        if is_connected(WP_ROW, TOP_RAIL):
            print("WP row %d is still on the top rail - refusing to add GND "
                  "(that would short the rail). Write test aborted." % WP_ROW)
            return i2c
        connect(WP_ROW, GND)
        moved = True
        time.sleep(0.05)
        i2c = open_bus()      # the re-route's refresh re-muxed 26/27
        if i2c is None:
            raise OSError("bus gone after the WP re-route")
        i2c.writeto_mem(ADDR, TEST_AT, bytes((probe,)), addrsize=ADDR_BITS)
        time.sleep(0.01)      # 24Cxx write cycle: 5 ms worst case
        back = i2c.readfrom_mem(ADDR, TEST_AT, 1, addrsize=ADDR_BITS)[0]
        print("wrote 0x%02X, read 0x%02X back - %s"
              % (probe, back, "writes work" if back == probe else "no stick"))
        i2c.writeto_mem(ADDR, TEST_AT, bytes((original,)), addrsize=ADDR_BITS)
        time.sleep(0.01)
        print("restored 0x%02X at 0x%02X." % (original, TEST_AT))
    except Exception as e:
        print("write test failed: " + str(e))
    finally:
        if moved:
            try:
                disconnect(WP_ROW, GND)
                connect(WP_ROW, TOP_RAIL)
                time.sleep(0.05)
                i2c = open_bus()
                print("write protect restored (row %d on the rail)." % WP_ROW)
            except Exception as e:
                print("COULD NOT RESTORE WRITE PROTECT: " + str(e))
                print("re-load the wiring before trusting the chip.")
    return i2c


def main():
    print("EEPROM Dumper " + str(_jl_project.get("dir", "")))
    i2c = open_bus()
    try:
        if i2c is None:
            return                  # inside the try: the finally still runs
        found = i2c.scan()
        print("i2c devices: " + str([hex(a) for a in found]))
        if ADDR not in found:
            print("no chip at " + hex(ADDR) + " - check the rail, the "
                  "pull-ups (rows 12/42 and 15/45) and A0-A2 to GND.")
            return
        data = read_block(i2c, 0x00, FIRST)
        hexdump(data, 0)
        blank = True
        for b in data:
            if b != 0xFF:
                blank = False
                break
        print("%d bytes read." % len(data) +
              ("  (all 0xFF - an erased chip)" if blank else ""))
        try:
            oled_print("EE %d B" % len(data))
        except Exception:
            pass
        more = ask("dump more - total size in bytes (blank = no): ")
        if more:
            total = int(more) if more.isdigit() else 0
            if total > FIRST:
                if ADDR_BITS == 8 and total > 256:
                    print("note: ADDR_BITS is 8, so past 0xFF wraps.")
                hexdump(read_block(i2c, FIRST, total - FIRST), FIRST)
                print("%d bytes read." % total)
        # WP is a wire the board owns, so read-only is topology here, not
        # convention. Default is no.
        print("Write test: one byte at 0x%02X, read back, original put "
              "back. WP moves to GND only for that." % TEST_AT)
        if ask("run the write test? [y/N] ").lower() == "y":
            i2c = write_test(i2c, data[TEST_AT] if len(data) > TEST_AT else 0xFF)
        else:
            print("skipped - the chip stays read-only.")
    except KeyboardInterrupt:
        print("")
    except Exception as e:
        print("failed: " + str(e))
    finally:
        release_bus()
        print("bye")


main()
)===";
const uint32_t PROJECT_EEPROM_MAIN_PY_HASHES[5] = { 0x1E5C7C14, 0x5E61C1F1, 0x0D73F0A3, 0x70FDD4AE, 0x9B89537B };
const int PROJECT_EEPROM_MAIN_PY_HASH_COUNT = 5;

const char* PROJECT_EEPROM_WIRING_YAML = R"===(version: 2
sourceOfTruth: bridges
meta:
  project: eeprom
  title: "EEPROM Dumper"
  variant: default
  summary: "Hex-dump a 24Cxx I2C EEPROM, with write protect held by the board"
  script: main.py
  needs: ["24C02 or 24C16 (DIP-8)", "4.7k", "4.7k"]
parts:
  - name: "U1"
    type: ic
    value: "24C02"
    footprint: dip8
    row: 35
    pins:
      A0:  {pin: 1, connect: GND,       class: signal}
      A1:  {pin: 2, connect: GND,       class: signal}
      A2:  {pin: 3, connect: GND,       class: signal}
      GND: {pin: 4, connect: GND,       class: gnd}
      SDA: {pin: 5, connect: RP_GPIO_7, class: signal}
      SCL: {pin: 6, connect: RP_GPIO_8, class: signal}
      WP:  {pin: 7, connect: TOP_RAIL,  class: signal}
      VCC: {pin: 8, connect: TOP_RAIL,  class: power}
  - name: "R1"
    type: resistor
    value: "4.7k"
    footprint: axial2
    row: 12
    pins: {A: {pin: 1, connect: TOP_RAIL}, B: {pin: 2, connect: 8}}
  - name: "R2"
    type: resistor
    value: "4.7k"
    footprint: axial2
    row: 15
    pins: {A: {pin: 1, connect: TOP_RAIL}, B: {pin: 2, connect: 7}}
guide:
  title: "EEPROM Dumper"
  steps:
    - {do: note, text: "A 24Cxx EEPROM on the I2C pins. Turn=prev/next, click=confirm, hold=exit."}
    - {do: place, part: U1, check: presence, on_fail: warn, text: "24Cxx across the middle gap, pin 1 (the dot) at row 35."}
    - {do: place, part: R1, check: continuity, text: "4.7k SDA pull-up: rows 12 and 42, straddling the middle gap."}
    - {do: place, part: R2, check: continuity, text: "4.7k SCL pull-up: rows 15 and 45, straddling the middle gap."}
    - {do: power_on, check: rail_sane, text: "Confirm to power the chip up (3.3V). WP is held high - reads only."}
    - {do: verify, target: 8, n1: 8, n2: 7, check: i2c, text: "Scanning the bus - a 24Cxx with A0-A2 grounded answers at 0x50."}
    - {do: note, text: "Built. Run main.py to hex-dump it."}
power:
  topRail: 3.3
config:
  gpio:
    pulls: [0,0,0,0,0,0,1,1,0,0]
)===";
const uint32_t PROJECT_EEPROM_WIRING_YAML_HASHES[2] = { 0x82F38CF1, 0x77CA786A };
const int PROJECT_EEPROM_WIRING_YAML_HASH_COUNT = 2;

#endif // INCLUDE_PROJECT_EEPROM

//---------- i2cscrn (scripts/projects/i2cscrn/) ----------
#ifdef INCLUDE_PROJECT_I2CSCRN
const char* PROJECT_I2CSCRN_README_MD = R"===(# Type to Screen

An I2C OLED module pushed into the breadboard - **anywhere** on it - wired to
the Jumperless's I2C pins by the crossbar. You type a line in the terminal, it
appears on the panel. No jumper wires: the Jumperless makes every connection.

## Parts you need

| Part | Package | Rows |
|------|---------|------|
| DISP | SSD1306 / SH1106 I2C module, 4-pin header | 5 - 8 *(the default; any rows work)* |

The guided build places the header in rows 5-8 in the usual pin order - **GND
5, VCC 6, SCL 7, SDA 8** - because a guide needs somewhere concrete to point.
But those rows are only a **default**: `main.py` asks where each signal
actually is, and re-routes to match. *Check your silkscreen before powering
up* - a few boards swap VCC and GND, and that is the one mistake that kills
the panel.

Top rail is set to 3.3 V. Whichever rows you use, SCL is routed to `RP_GPIO_8`
(RP pin 27) and SDA to `RP_GPIO_7` (RP pin 26) - the same pair the built-in
I2C scanner uses. Those two are fixed by the hardware; only the breadboard row
is yours to choose.

> **Jumperless V5 only.** This project routes breadboard rows to
> `RP_GPIO_7` and `RP_GPIO_8`, and those nodes exist only on the V5. The original
> Jumperless has exactly three routable GPIO (`RP_GPIO_0` plus UART
> TX/RX), so the wiring loads there but cannot be routed.

## What it does

`main.py` runs four steps, in order.

**1. Tap-to-assign.** It asks where each of GND / VCC / SCL / SDA is. At every
one of those prompts you can **tap the hole with the probe** *or* **type the
row number** - both are live at the same time, and pressing enter alone keeps
the default. Every probe gesture here has a typed twin, which is what makes
the whole flow drivable from a terminal, from a script, and from the HIL:

    Where is the panel? Enter alone keeps the guide's header rows.
      GND  tap its hole with the probe, or type a row 1-60 (enter = 5, q = quit)
           GND = row 5 (default)
      VCC  tap its hole with the probe, or type a row 1-60 (enter = 6, q = quit)
           VCC = row 41 (tapped)
      ...
    assignment: GND 5  VCC 41  SCL 7  SDA 8

**2. Driver and size.** A three-item menu - enter picks the first:

    Panel type:
      1) SSD1306 128x32   (default)
      2) SSD1306 128x64
      3) SH1106  128x64

**3. The wiring beacon.** It routes what you assigned, then loops: scan the
bus, and the moment something answers, initialise it and start drawing an
animation. **You can wire the panel up while this is running** and watch it
spring to life the instant the last wire is right. The terminal shows a quiet
row of dots, not one error per attempt:

    waiting for the panel - wire it up now ('q' + enter to give up)
    ............
    panel up at 0x3c: 128x32, 4 rows of 16 chars

**4. Type to screen.** Each line you type is pushed onto a short history and
redrawn. An empty line clears, `q` quits, Ctrl-C works. If the panel falls off
the bus mid-session, the script drops back to the beacon instead of dying -
push the module back in and it comes straight back.

The driver is deliberately tiny: MicroPython's `framebuf` module supplies the
pixel buffer and the built-in 8x8 font, and the `Screen` class only adds the
command set. **The SH1106 shim is two small differences**, both in `Screen`:
its charge pump is `0xAD/0x8B` instead of `0x8D/0x14`, and it has no
memory-addressing-mode command at all - so `show()` sets the page pointer per
page and starts each row at **column 2**, because the SH1106's RAM is 132
columns wide with the glass wired to 2..129. Miss that offset and the whole
image sits two pixels left, wrapped.

### What it leaves behind: nothing of its own

On the way out - `q`, Ctrl-C, or any other exit - the script blanks the panel,
releases its GPIO claims, and **removes exactly the bridges it made**. It
records each route as it makes it, and a route that was already on the board
when it started is reported and left alone:

    GND row 5 -> GND was already routed - left alone
    SDA row 8 -> RP_GPIO_7

That is the deliberate reading of "clear the data lines on exit": *this script
cleans up after itself*, and a guided build's bridges are your saved circuit,
not its mess. Run it after a guided build and it will find all four routes
already there, make none, and remove none.

### No prompt needs a keyboard

Every question this script asks answers to all three surfaces, and the wheel
alone is enough to get from launch to a working screen:

| | probe | clickwheel | terminal |
|---|---|---|---|
| **which row is this signal in** | tap the hole (absolute) | turn to nudge the row, click to take it | type `1`-`60`, or enter for the default |
| **which panel do you have** | — | turn the list, click to take it | type `1`-`3`, or enter for the default |
| **give up** | — | hold | `q` |

**One direction rule everywhere: up = previous / −1, down = next / +1**, click
takes, hold quits. The wheel has no double-click; two fast presses are two
ordinary clicks, so nothing here breaks if you click twice.

The panel-type question used to be typing-only, which quietly made a keyboard
mandatory for a flow that otherwise never needed one. The current OLED shows
the candidate row or panel name as you turn, so the whole thing is usable with
the terminal closed.

Because typed input still answers everything, the flow stays scriptable over
the serial port: launch it (`z i2cscrn`, or the Files browser) and send `5`,
`6`, `41`, `42`, `2`, `q` as lines. That is exactly how `test_projects.py`
exercises it with no panel attached - through the real launcher, the real
prompts and the real stdin.

> **A note on script size.** Until wave 3 the launcher needed *two* full-size
> copies of the source in RAM to prepend `_jl_project`, against an Arduino heap
> that settles around 19 KB free - so anything past roughly 6 KB failed, and
> failed **silently**, printing `Running ...` and then `--- script finished ---`
> with nothing between. Fixed in `runCompanionScript`
> (`src/ProjectsApp.cpp`): **the source is never copied into RAM at all**. The
> runner hands MicroPython a short `execfile()` and the lexer streams the script
> off the filesystem, so there is no Arduino-side ceiling left, and every
> failure branch now prints.
>
> One bound survives, a level up: **MicroPython's compiler** needs heap
> proportional to the source. Measured on this board: **13 KB runs on a fresh
> boot, 15 KB raises `MemoryError` even there** - and much less than 13 KB
> survives deep into a long session, because the interpreter heap never resets
> between scripts. This script is about 13 KB and that is the ceiling, not a
> comfortable middle. If you add to it, take the space back out of the prose
> (which belongs in this file) rather than out of the margin.

## Running it

- **Clickwheel:** `Guides` - it is a top-level menu row, before `Apps` - then
  **i2cscrn**, and walk the guided build. That is what wires the parts up. Run
  `main.py` when it offers at the end.
- **Headless:** `z i2cscrn` on the terminal drives the same flow. Add `new` to
  start over from the wiring, `load` to reopen the run you already have,
  `noscript` to stop at the wiring.
- **`main.py` on its own** is enough if you would rather not walk the guide at
  all: it does its own assignment and its own routing, so a module dropped in
  any four rows comes up from a bare board.

Launching a project does not borrow a slot any more. It opens
`/projects/i2cscrn/i2cscrn_run.yaml` - a **run file** - and makes it your active
circuit, exactly as if you had clicked a YAML in the Files browser. There is
**one run file per project** and it is reused: your build is saved into it at
every step, the board comes back to it after a power cycle, and the next launch
reopens it silently - unless you quit a guided build part way through, in which
case you are asked once whether to resume or to start over. To keep a run,
`slots` > `save to` while it is active. The shipped `wiring.yaml` is a
read-only template and is never written to.

Clicking `wiring.yaml` in the Files browser starts a run the same way. Either
route, **only a guide commit wires a part**: `expandPartsToBridges()` skips any
part still marked `placed: false`. This project has no `bridges:` section at
all, so a run you have not walked through yet has **nothing** on the
breadboard.

## Moving parts around

**Compact vs expanded.** Every two-leg part can sit two ways. **Expanded** puts
it at its own rows and the Jumperless routes its connections through the
crossbar underneath - good while you are building, because each part is easy to
see and to test on its own. **Compact** is how you would breadboard it by hand:
the legs go straight into the rows they connect to - a resistor from a chip's
pin row to the rail goes leg-in-row-7, leg-in-the-rail - and the routed
connections for that part disappear, because the legs themselves make the
contact.

Tap a part's lit footprint with the probe to flip that one part between the
two. **Every part remembers its own setting.** A leg whose endpoint is not a
real hole - `GND` and the analog pins live in the crossbar, not on the board -
keeps its own row and its routed connection either way, so a compact part can
still have one bridge.

To **move** a part, tap any free hole and pin 1 jumps there. The wheel never
moves a part - it only browses the steps. On the terminal, `m <row>` and `c` do
the same two things the probe does. Chips (DIPs) sit with pin 1 - the dot or
the notch - wherever it really sits: **bottom-left** (rows 31-60) or rotated
180 with pin 1 top-right (rows 1-30). Axial parts (resistors, diodes) straddle the
middle gap by default; radial parts (caps, LEDs) sit in two neighbouring rows.

**Browsing.** The wheel moves *between* steps rather than confirming them, and
the ring wraps: turn past the last step and you land on a summary of what is
built, skipped and still outstanding; turn again and you are back at step 1. A
turn never ends the build - hold the wheel, or press `q`, for that. You can skip
a part with `s` and come back to it later, and confirming at the summary jumps
you to the first thing you have not built yet.

> Measuring and *identifying* an unknown part (`identify_part(leftmost_row=...)`)
> is planned but is not in this release. What the guide shows today is the value
> each verify step measures - a resistance, a diode drop, a rail voltage.

## Troubleshooting

- **The dots never stop** - nothing is acking. The beacon is the diagnostic:
  leave it running and re-seat one wire at a time. Check GND and VCC first (a
  panel with no power cannot ack anything), then that the rows you assigned are
  the rows the legs are actually in, then the SDA/SCL order.
- **"panel up at 0x3c" then "panel went away (ETIMEDOUT)", over and over** -
  fixed 2026-08-23, and worth knowing why. A full 128x32 frame is 513 bytes;
  at 100 kHz that is 513 x 9 bits = **~46 ms** of bus time, and `machine.I2C`'s
  **default timeout is 50 ms**. Every frame ran 4 ms from the edge, so the
  panel initialised, drew its splash, and then threw `ETIMEDOUT` the moment
  anything - a stretched clock, a slow rise through the crossbar - ate the
  margin. The beacon read that as the panel vanishing and went back to
  scanning, forever. `I2C_TIMEOUT_US` is now 400 ms, roughly 8x the frame; a
  128x64 panel needs twice the bus time and still clears it comfortably.
- **Every address answers (a "bus" of 100+ devices)** - that is not devices,
  it is SDA unable to rise, so the master reads its own low back as an ack
  from everyone. Almost always a missing pull-up: the internal one is ~50k,
  far too weak to pull a routed breadboard net up inside a 100 kHz bit time.
  A 4-pin module brings its own; a bare panel needs 4.7k. The script says so
  in as many words rather than pretending it found a hundred chips.
- **Wrong rows assigned** - `q`, enter, and run it again. Nothing is
  remembered between runs, and the exit removed whatever it had routed.
- **A device answers, but at some other address** - the script tries `0x3C`
  and `0x3D`, which covers effectively every module. Anything else: add it to
  `ADDRS` at the top of `main.py`.
- **The panel lights up but the image is shifted two pixels and wrapped** -
  it is an SH1106, not an SSD1306. Pick option 3.
- **Bare panel, no breakout board** - the 4-pin modules carry their own
  pull-up resistors. A raw panel does not; add 4.7k from row 7 and from
  row 8 up to the top rail (that is exactly what the `eeprom` project
  does for its bare chip).
- **The Jumperless's own top OLED behaves oddly while this runs** - in its
  default `connection_type 0` it lives on GPIO 7/8, the very pins this
  project uses, and it shares the i2c1 peripheral in every mode. Turn it
  off (or move it to the hardwired pins) while you play with this project.
- **The screen shows garbage after a while** - drop `I2C_HZ` to 50000.
  Long crossbar paths plus breadboard capacitance slow the edges down.
)===";
const uint32_t PROJECT_I2CSCRN_README_MD_HASHES[11] = { 0xD4A9C754, 0x6AF0D1BF, 0x6392E24F, 0xBCF87B83, 0x185ED360, 0x08C60795, 0x5D79CA91, 0xF62F698B, 0x9006DDCB, 0x4A5A7256, 0xBFC48EF5 };
const int PROJECT_I2CSCRN_README_MD_HASH_COUNT = 11;

const char* PROJECT_I2CSCRN_MAIN_PY = R"===("""Type to Screen - companion for /projects/i2cscrn/wiring.yaml, see README.md.

An I2C OLED wired anywhere on the breadboard, typed at. Every prompt answers to
probe, wheel AND terminal, and only the bridges made here are removed.

KEEP UNDER ~13 KB - it is compiled on-device from one never-resetting heap, and
15 KB raises MemoryError even on a fresh boot. Prose goes in README.md.
"""

import sys
import time

_jl_project = globals().get("_jl_project", {})

SDA_PIN = 26           # RP_GPIO_7 \ fixed by the hardware; only the
SCL_PIN = 27           # RP_GPIO_8 / breadboard row is yours to choose
I2C_HZ = 100000
# Must clear a full frame: 513 B is ~46 ms at 100 kHz vs a 50 ms default -
# that 4 ms of margin was the ETIMEDOUT "panel went away" loop. Sum in README.
I2C_TIMEOUT_US = 400000
ADDRS = (0x3C, 0x3D)

# label, kind, width, height. First is the default.
DRIVERS = (("SSD1306 128x32", "ssd1306", 128, 32),
           ("SSD1306 128x64", "ssd1306", 128, 64),
           ("SH1106  128x64", "sh1106", 128, 64))

# signal, default row (the guide's placement), node it must reach.
SIGNALS = (("GND", 5, "GND"), ("VCC", 6, "TOP_RAIL"),
           ("SCL", 7, "RP_GPIO_8"), ("SDA", 8, "RP_GPIO_7"))

RETRY_MS = 300         # beacon rescan interval
SPLASH_MS = 2500       # animate this long before the type loop


class Abort(Exception):
    pass


try:
    import select
    _poll = select.poll()
    _poll.register(sys.stdin, select.POLLIN)
except Exception:
    _poll = None
_inbuf = ""
_lastcr = False


def ask():
    """A typed line once enter arrives, else None. Never blocks."""
    global _inbuf, _lastcr
    if _poll is None:
        return input()
    try:
        if not _poll.poll(0):
            return None
        ch = sys.stdin.read(1)
    except Exception:
        return None
    if not ch:
        return None
    if ch == "\x03":
        raise KeyboardInterrupt
    if ch in ("\n", "\r"):
        # A terminal that sends CRLF must not count as two Enters - the second
        # one would silently take the default for the NEXT signal.
        if ch == "\n" and _lastcr:
            _lastcr = False
            return None
        _lastcr = (ch == "\r")
        line, _inbuf = _inbuf, ""
        print()
        return line
    _lastcr = False
    if ch in ("\x08", "\x7f"):
        if _inbuf:
            _inbuf = _inbuf[:-1]
            print("\b \b", end="")
        return None
    _inbuf += ch
    print(ch, end="")
    return None


def drain():
    """Swallow buffered input - the launching newline would answer prompt 1."""
    global _inbuf, _lastcr
    if _poll is None:
        return
    end = time.ticks_ms()
    while time.ticks_diff(time.ticks_ms(), end) < 200:
        try:
            if _poll.poll(0):
                sys.stdin.read(1)
                continue
        except Exception:
            break
        time.sleep(0.01)
    _inbuf, _lastcr = "", False


def say(text):
    try:
        oled_print(text)
    except Exception:
        pass


_wbtn = 0


HELDS = (2, 5, 6)      # HELD, LONG_HELD, MEDIUM_HELD - all mean "quit"


def wheel():
    """'up'|'down'|'click'|'hold'|None. up=-1, down=+1, click takes, hold quits.

    Click is edge-triggered on ENTERING released, not on having seen PRESSED:
    the injected press writes RELEASED straight out. Ending a hold is no click.
    """
    global _wbtn
    try:
        d = clickwheel_get_direction()
        b = clickwheel_get_button()
    except Exception:
        return None
    if d == 1:
        return "up"
    if d == 2:
        return "down"
    was, _wbtn = _wbtn, b
    if b in HELDS:
        return "hold"
    if b == 3 and was != 3:
        return None if was in HELDS else "click"
    return None


def choose(lo, hi, start, render, probe=False, dflt=None):
    """The loop both prompts share: wheel turns/clicks, probe taps (rows only),
    terminal types, enter takes the default. Wraps, never runs off the end.
    Returns (value, which surface answered) - the provenance is worth saying
    out loud, and it is what the HIL suite reads to know a typed answer landed
    as typed."""
    v = start
    render(v)
    while True:
        w = wheel()
        if w == "hold":
            raise Abort()
        if w == "up" or w == "down":
            v = lo + (v - lo + (-1 if w == "up" else 1)) % (hi - lo + 1)
            render(v)
            continue
        if w == "click":
            return v, "wheel"
        line = ask()
        if line is not None:
            t = line.strip().lower()
            if t in ("q", "quit"):
                raise Abort()
            if t == "":
                return (dflt if dflt is not None else v), "default"
            if t.isdigit() and lo <= int(t) <= hi:
                return int(t), "typed"
            print("  ? %d-%d, or use the wheel" % (lo, hi))
        if probe:
            try:
                pad = probe_read(False)
                pv = -1 if pad == NO_PAD else int(pad)
            except Exception:
                pv = -1
            if lo <= pv <= hi:
                return pv, "tapped"
        time.sleep(0.02)


def ask_row(name, default):
    print("  %-3s  tap it, turn+click the wheel, or type 1-60 (enter=%d, q)"
          % (name, default))

    def show(v):
        say("Tap %s\nor row %d" % (name, v))
        print("       %s -> row %-3d\r" % (name, v), end="")

    r, how = choose(1, 60, default, show, True, default)
    print("\n       %s = row %d (%s)" % (name, r, how))
    return r


def ask_driver():
    print("Panel type: turn the wheel and click, or type 1-%d" % len(DRIVERS))
    for n, d in enumerate(DRIVERS):
        print("  %d) %s%s" % (n + 1, d[0], "   (default)" if n == 0 else ""))

    def show(v):
        say("Panel?\n%s" % DRIVERS[v - 1][0])
        print("   > %-16s\r" % DRIVERS[v - 1][0], end="")

    d = DRIVERS[choose(1, len(DRIVERS), 1, show, False, 1)[0] - 1]
    print("\ndriver: %s (%s %dx%d)" % d)
    return d


# Only what WE made - after a guided build the rest is the user's circuit.
made = []


def route(rows):
    for name, _d, node in SIGNALS:
        row = rows[name]
        try:
            if is_connected(row, node):
                # Wording is a contract: test_projects reads this line, and
                # "left alone" is what tells the user their wiring survived.
                print("  %s row %d -> %s was already routed - left alone"
                      % (name, row, node))
                continue
            connect(row, node)
            made.append((row, node))
            print("  %s row %d -> %s" % (name, row, node))
        except Exception as e:
            print("  could not route %s: %s" % (name, str(e)))
    print("routed=%d" % len(made))
    try:
        v = dac_get("TOP_RAIL")
        print("top rail: %.2f V" % v)
        if v < 3.0 or v > 5.5:
            print("  WARNING: outside 3.0-5.5 V (this never sets a rail)")
    except Exception:
        pass


def unroute():
    n = 0
    while made:
        row, node = made.pop()
        try:
            disconnect(row, node)
            n += 1
        except Exception:
            pass
    print("unrouted=%d" % n)


def pins(claim):
    # Or refreshConnections() re-asserts config pulls under the peripheral.
    for n in (GPIO_7, GPIO_8):
        try:
            gpio_claim_pin(n) if claim else gpio_release_pin(n)
        except Exception:
            pass


class Screen:
    def __init__(self, i2c, addr, kind, w, h):
        import framebuf
        self.i2c, self.addr, self.kind = i2c, addr, kind
        self.w, self.h, self.pages = w, h, h // 8
        self.buf = bytearray(self.pages * w)
        self.fb = framebuf.FrameBuffer(self.buf, w, h, framebuf.MONO_VLSB)
        self.tx = bytearray(1 + len(self.buf))
        self.tx[0] = 0x40                    # "data follows"
        self.rows, self.cols = self.pages, w // 8
        # SH1106 shim 1/2: pump is 0xAD/0x8B and it has no 0x20 command.
        pump = (0xAD, 0x8B) if kind == "sh1106" else (0x8D, 0x14, 0x20, 0x00)
        for c in ((0xAE, 0xD5, 0x80, 0xA8, h - 1, 0xD3, 0x00, 0x40) + pump +
                  (0xA1, 0xC8, 0xDA, 0x02 if h == 32 else 0x12, 0x81, 0xCF,
                   0xD9, 0xF1, 0xDB, 0x40, 0xA4, 0xA6, 0xAF)):
            self.cmd(c)

    def cmd(self, c):
        self.i2c.writeto(self.addr, bytes((0x00, c)))

    def show(self):
        if self.kind == "sh1106":
            # Shim 2/2: page pointer per page from column 2 (132-wide RAM).
            mv = memoryview(self.tx)
            for pg in range(self.pages):
                self.cmd(0xB0 | pg); self.cmd(0x02); self.cmd(0x10)
                s = pg * self.w
                self.tx[1:1 + self.w] = self.buf[s:s + self.w]
                self.i2c.writeto(self.addr, mv[:1 + self.w])
            return
        self.cmd(0x21); self.cmd(0); self.cmd(self.w - 1)
        self.cmd(0x22); self.cmd(0); self.cmd(self.pages - 1)
        self.tx[1:] = self.buf
        self.i2c.writeto(self.addr, self.tx)

    def lines(self, texts):
        self.fb.fill(0)
        y = 0
        for t in texts:
            self.fb.text(t[:self.cols], 0, y, 1)
            y += 8
        self.show()

    def splash(self, frame):
        self.fb.fill(0)
        self.fb.text("JUMPERLESS", max(0, (self.w - 80) // 2), 0, 1)
        self.fb.text("type to screen", max(0, (self.w - 112) // 2), 10, 1)
        self.fb.fill_rect((frame * 8) % (self.w + 32) - 32, self.h - 6, 32, 4, 1)
        self.show()


def beacon(i2c, kind, w, h):
    """Rescan until answered, then animate. Quit check is at the BOTTOM."""
    print("waiting for the panel - wire it up now (hold the wheel or 'q' to"
          " give up)")
    say("Waiting\nfor panel")
    scr = None
    frame = dots = splash_at = 0
    last = None
    stuck = False
    while True:
        nap = 0.02
        if scr is None:
            now = time.ticks_ms()
            if last is None or time.ticks_diff(now, last) >= RETRY_MS:
                last = now
                try:
                    found = i2c.scan()
                except Exception:
                    found = []
                if len(found) > 8:
                    # Not a bus full of chips - SDA cannot rise, so the master
                    # reads its own low back as an ACK from everyone.
                    if not stuck:
                        stuck = True
                        print("\nevery address answered - SDA stuck low, not"
                              " %d devices; check SDA's row and its pull-up"
                              % len(found))
                    found = []
                addr = None
                for a in ADDRS:
                    if a in found:
                        addr = a
                if addr is not None:
                    try:
                        scr = Screen(i2c, addr, kind, w, h)
                        print("\npanel up at %s: %dx%d, %d rows of %d chars"
                              % (hex(addr), w, h, scr.rows, scr.cols))
                        say("Panel\nup!")
                        splash_at, frame = time.ticks_ms(), 0
                    except Exception as e:
                        print("\n%s would not init: %s" % (hex(addr), str(e)))
                        scr = None
                if scr is None:
                    dots += 1
                    print(".", end="")
                    if dots % 40 == 0:
                        print("  (nothing yet - check GND/VCC, then SDA/SCL"
                              " order)")
        else:
            try:
                scr.splash(frame)
            except Exception as e:
                print("panel went away (%s) - back to waiting" % str(e))
                scr, dots, last = None, 0, None
            else:
                frame += 1
                if time.ticks_diff(time.ticks_ms(), splash_at) >= SPLASH_MS:
                    return scr
                nap = 0.08
        if wheel() == "hold":
            raise Abort()
        line = ask()
        if line is not None and line.strip().lower() in ("q", "quit"):
            raise Abort()
        time.sleep(nap)


print("Type to Screen")
if _jl_project:
    print("project: " + str(_jl_project.get("dir", "i2cscrn")))

scr = None
try:
    drain()
    print("Where is the panel? Enter alone keeps the guide's rows.")
    rows = {}
    for _nm, _df, _nd in SIGNALS:
        rows[_nm] = ask_row(_nm, _df)
    print("assignment: " + "  ".join("%s %d" % (n, rows[n])
                                     for n, _d, _x in SIGNALS))
    label, kind, w, h = ask_driver()
    pins(True)
    route(rows)
    import machine
    i2c = machine.I2C(1, scl=SCL_PIN, sda=SDA_PIN, freq=I2C_HZ,
                      timeout=I2C_TIMEOUT_US)
    scr = beacon(i2c, kind, w, h)

    print("Type a line + enter. Empty clears. 'q' or hold quits.")
    history = []
    print("> ", end="")
    while True:
        if wheel() == "hold":
            break
        typed = ask()
        if typed is None:
            time.sleep(0.02)
            continue
        if typed.strip().lower() in ("q", "quit"):
            break
        if typed == "":
            history = []
        else:
            history.append(typed)
            history = history[-scr.rows:]
        try:
            scr.lines(history)
        except Exception as e:
            print("write failed (%s) - back to the beacon" % str(e))
            scr = beacon(i2c, kind, w, h)
        print("> ", end="")
except (KeyboardInterrupt, Abort):
    pass
except Exception as e:
    print("stopped: " + str(e))
finally:
    # finally, not the except arms: every exit path restores the board.
    if scr is not None:
        try:
            scr.lines([])
        except Exception:
            pass
    unroute()
    pins(False)
    print("bye")
)===";
const uint32_t PROJECT_I2CSCRN_MAIN_PY_HASHES[11] = { 0x024D8AA9, 0x59E93C91, 0xE21C8E8E, 0x6E22A6DD, 0xBEFB8273, 0xF166AB80, 0xCB6D158D, 0x6D63CA5E, 0x5883C818, 0xDC3D3F52, 0x79C8D0B3 };
const int PROJECT_I2CSCRN_MAIN_PY_HASH_COUNT = 11;

const char* PROJECT_I2CSCRN_WIRING_YAML = R"===(version: 2
sourceOfTruth: bridges
meta:
  project: i2cscrn
  title: "Type to Screen"
  variant: default
  summary: "An SSD1306 on the breadboard, echoing whatever you type"
  script: main.py
  needs: ["SSD1306 I2C module (4-pin: GND VCC SCL SDA)"]
parts:
  - name: "DISP"
    type: ic
    value: "SSD1306"
    footprint: sip4
    row: 5
    pins:
      GND: {pin: 1, connect: GND,       class: gnd}
      VCC: {pin: 2, connect: TOP_RAIL,  class: power}
      SCL: {pin: 3, connect: RP_GPIO_8, class: signal}
      SDA: {pin: 4, connect: RP_GPIO_7, class: signal}
guide:
  title: "Type to Screen"
  steps:
    - {do: note, text: "An SSD1306 the Jumperless talks to. Turn=prev/next, click=confirm, hold=exit."}
    - {do: place, part: DISP, check: presence, on_fail: warn, text: "Header in rows 5-8: GND 5, VCC 6, SCL 7, SDA 8. Check the silkscreen order."}
    # 5-8 is the DEFAULT, not a requirement: main.py asks where each signal
    # actually is (tap the hole, or type the row) and re-routes to match. The
    # guide places it here so there is something concrete to build against.
    - {do: power_on, check: rail_sane, text: "Confirm to power the display (3.3V on the top rail)."}
    - {do: verify, target: 8, n1: 8, n2: 7, check: i2c, text: "Scanning the bus - the panel should answer (0x3C on nearly every module)."}
    - {do: note, text: "Wired. Run main.py: it asks where each signal is, offers a driver list, then waits for the panel."}
power:
  topRail: 3.3
config:
  gpio:
    pulls: [0,0,0,0,0,0,1,1,0,0]
)===";
const uint32_t PROJECT_I2CSCRN_WIRING_YAML_HASHES[2] = { 0xB48355B8, 0xBEE331D0 };
const int PROJECT_I2CSCRN_WIRING_YAML_HASH_COUNT = 2;

#endif // INCLUDE_PROJECT_I2CSCRN

//---------- nand00 (scripts/projects/nand00/) ----------
#ifdef INCLUDE_PROJECT_NAND00
const char* PROJECT_NAND00_README_MD = R"(# Logic Gates 101

A 74HC00 quad NAND gate. The Jumperless drives both inputs of gate 1, reads
its output back, and lights an LED from the same output - so you can watch
the truth table and measure it at the same time.

## Parts you need

| Part | Value | Package | Rows |
|------|-------|---------|------|
| U1   | 74HC00 | DIP-14 | pin 1 at row 35, across the middle gap |
| LED1 | any   | 2-lead  | anode (long leg) 18, cathode 19 |
| R1   | 330   | axial   | 15 - 45, straddling the middle gap |

Top rail is set to **3.3 V**, not 5 V: rows 35, 36 and 37 land on real RP2350
pins, and those are 3.3 V parts. A 74HC00 is perfectly happy anywhere from
2 V to 6 V.

Pin map for gate 1:

| 74HC00 pin | Row | Goes to |
|---|---|---|
| 1 (1A) | 35 | `RP_GPIO_1` - the Jumperless drives it |
| 2 (1B) | 36 | `RP_GPIO_2` - the Jumperless drives it |
| 3 (1Y) | 37 | `RP_GPIO_3` for readback, and R1 -> LED1 -> GND |
| 7 (GND) | 41 | GND |
| 14 (VCC) | 5 | top rail |

> **Jumperless V5 only.** This project routes breadboard rows to
> `RP_GPIO_1`, `RP_GPIO_2` and `RP_GPIO_3`, and those nodes exist only on the V5. The original
> Jumperless has exactly three routable GPIO (`RP_GPIO_0` plus UART
> TX/RX), so the wiring loads there but cannot be routed.

The other three gates are not used, so their inputs (pins 4, 5, 9, 10, 12,
13) are tied to GND. That is not decoration: a floating CMOS input drifts
around its switching threshold, oscillates, and makes the chip draw far more
current than it should.

## What it does

      A  B  | Y  expected  LED
      ------+-----------------
      0  0  | 1  1         on    ok
      0  1  | 1  1         on    ok
      1  0  | 1  1         on    ok
      1  1  | 0  0         off   ok

    All four rows match NAND. That is a working gate.

NAND is "not and": the output is high unless **both** inputs are high. So
the LED is lit for three of the four input combinations and dark for the
fourth.

After the table, `main.py` drops into a live mode. Type `10` and the board
sets A high, B low, and reads the result back:

    A B> 10
       A=1 B=0 -> Y = HIGH (expected 1)

`q` quits, and Ctrl-C works too.

## Running it

- **Clickwheel:** `Guides` - it is a top-level menu row, before `Apps` - then
  **nand00**, and walk the guided build. That is what wires the parts up. Run
  `main.py` when it offers at the end.
- **Headless:** `z nand00` on the terminal drives the same flow. Add `new` to
  start over from the wiring, `load` to reopen the run you already have,
  `noscript` to stop at the wiring.

Launching a project does not borrow a slot any more. It opens
`/projects/nand00/nand00_run.yaml` - a **run file** - and makes it your active
circuit, exactly as if you had clicked a YAML in the Files browser. There is
**one run file per project** and it is reused: your build is saved into it at
every step, the board comes back to it after a power cycle, and the next launch
reopens it silently - unless you quit a guided build part way through, in which
case you are asked once whether to resume or to start over. To keep a run,
`slots` > `save to` while it is active. The shipped `wiring.yaml` is a
read-only template and is never written to.

Clicking `wiring.yaml` in the Files browser starts a run the same way. Either
route, **only a guide commit wires a part**: `expandPartsToBridges()` skips any
part still marked `placed: false`. This project has no `bridges:` section at
all, so a run you have not walked through yet has **nothing** on the
breadboard.

## Moving parts around

**Compact vs expanded.** Every two-leg part can sit two ways. **Expanded** puts
it at its own rows and the Jumperless routes its connections through the
crossbar underneath - good while you are building, because each part is easy to
see and to test on its own. **Compact** is how you would breadboard it by hand:
the legs go straight into the rows they connect to - a resistor from a chip's
pin row to the rail goes leg-in-row-7, leg-in-the-rail - and the routed
connections for that part disappear, because the legs themselves make the
contact.

Tap a part's lit footprint with the probe to flip that one part between the
two. **Every part remembers its own setting.** A leg whose endpoint is not a
real hole - `GND` and the analog pins live in the crossbar, not on the board -
keeps its own row and its routed connection either way, so a compact part can
still have one bridge.

To **move** a part, tap any free hole and pin 1 jumps there. The wheel never
moves a part - it only browses the steps. On the terminal, `m <row>` and `c` do
the same two things the probe does. Chips (DIPs) sit with pin 1 - the dot or
the notch - wherever it really sits: **bottom-left** (rows 31-60) or rotated
180 with pin 1 top-right (rows 1-30). Axial parts (resistors, diodes) straddle the
middle gap by default; radial parts (caps, LEDs) sit in two neighbouring rows.

**Browsing.** The wheel moves *between* steps rather than confirming them, and
the ring wraps: turn past the last step and you land on a summary of what is
built, skipped and still outstanding; turn again and you are back at step 1. A
turn never ends the build - hold the wheel, or press `q`, for that. You can skip
a part with `s` and come back to it later, and confirming at the summary jumps
you to the first thing you have not built yet.

> Measuring and *identifying* an unknown part (`identify_part(leftmost_row=...)`)
> is planned but is not in this release. What the guide shows today is the value
> each verify step measures - a resistance, a diode drop, a rail voltage.

## Troubleshooting

- **Every read says `FLOATING`** - the output pin is not driving. Check that
  the chip straddles the middle gap with pin 1 (next to the notch) at row 35,
  and that the top rail really is at 3.3 V.
- **The LED never lights but the readback is right** - the LED is backwards.
  The long leg goes in row 18.
- **The LED is on for all four rows** - the output is stuck high. Most often
  input pin 1 or 2 is not seated: a floating HC input drifts high, and two
  high inputs are the only case NAND pulls low.
- **The LED is on for exactly one row, `1 1`** - that is a 74HC**08** (AND).
  AND is NAND's exact inverse, so it lights the one row NAND darkens. Check
  the part number on the chip.
- **A 74HC02 (NOR) is worse than wrong here.** Its pin 1 is an *output*
  (1Y), not an input, and this wiring drives pin 1 from `RP_GPIO_1` - two
  drivers fighting over one node. Pull it out rather than leaving it
  powered, and use a 74HC00.
- **The last two rows disagree** - one of the two input legs (rows 35, 36) is
  not making contact.
)";
const uint32_t PROJECT_NAND00_README_MD_HASHES[9] = { 0x16FA909C, 0x3D3A125D, 0x1B3E29C7, 0xA7C19863, 0x94003C75, 0x59A4BE23, 0x36273393, 0x6F684328, 0x66A8E629 };
const int PROJECT_NAND00_README_MD_HASH_COUNT = 9;

const char* PROJECT_NAND00_MAIN_PY = R"("""Logic Gates 101 - companion script for /projects/nand00/wiring.yaml

Gate 1 of a 74HC00 is wired so the Jumperless owns all three of its pins:
GPIO_1 -> pin 1 (A), GPIO_2 -> pin 2 (B), pin 3 (Y) -> GPIO_3 and the LED.
So the board can drive the inputs, read the output back, and check the chip
against the truth table it is supposed to obey.

Runs standalone from the Files browser too - the launcher injects
_jl_project, but nothing here depends on it.
"""

import time

# The launcher injects this global; default so the script also runs standalone.
_jl_project = globals().get("_jl_project", {})

IN_A = GPIO_1       # node 131 -> row 35 -> 74HC00 pin 1
IN_B = GPIO_2       # node 132 -> row 36 -> 74HC00 pin 2
OUT = GPIO_3        # node 133 -> row 37 -> 74HC00 pin 3

SETTLE_S = 0.02     # the gate switches in nanoseconds; this is for the LED


def setup():
    gpio_set_dir(IN_A, True)      # True = OUTPUT
    gpio_set_dir(IN_B, True)
    gpio_set_dir(OUT, False)      # False = INPUT
    gpio_set_pull(OUT, 0)         # no pull - the 74HC00 drives this line
    gpio_set(IN_A, False)
    gpio_set(IN_B, False)


def read_out():
    """(state_object, text, bit_or_None). bit is None when the line floats."""
    s = gpio_get(OUT)
    t = str(s)
    if s == 1:
        return s, t, 1
    if s == 0:
        return s, t, 0
    return s, t, None


def apply(a, b):
    gpio_set(IN_A, bool(a))
    gpio_set(IN_B, bool(b))
    time.sleep(SETTLE_S)
    return read_out()


print("Logic Gates 101 - 74HC00 NAND")
if _jl_project:
    print("project: " + str(_jl_project.get("dir", "nand00")) +
          "  variant: " + str(_jl_project.get("variant", "default")))

setup()

print("")
print("  A  B  | Y  expected  LED")
print("  ------+-----------------")

wrong = 0
floated = 0
for a, b in ((0, 0), (0, 1), (1, 0), (1, 1)):
    state, text, bit = apply(a, b)
    expected = 0 if (a and b) else 1
    if bit is None:
        floated += 1
        verdict = "FLOATING"
    elif bit != expected:
        wrong += 1
        verdict = "WRONG"
    else:
        verdict = "ok"
    print("  %d  %d  | %s  %d         %s   %s"
          % (a, b, ("1" if bit == 1 else "0" if bit == 0 else "?"),
             expected, "on " if expected else "off", verdict))

print("")
if floated:
    print("%d of 4 reads floated - is the 74HC00 seated, and is the rail on?"
          % floated)
elif wrong:
    print("%d of 4 rows disagree with NAND - wrong chip, or a leg not in "
          "its hole?" % wrong)
else:
    print("All four rows match NAND. That is a working gate.")

try:
    oled_print("NAND ok" if (not wrong and not floated) else "NAND ??")
except Exception:
    pass

print("")
print("Live mode: type two bits (00, 01, 10, 11) to set the inputs.")
print("Empty line re-reads without changing anything. 'q' quits.")

try:
    while True:
        try:
            typed = input("A B> ").strip()
        except EOFError:
            break
        if typed == "q":
            break
        if typed == "":
            state, text, bit = read_out()
            print("   Y = " + text)
            continue
        digits = [c for c in typed if c in "01"]
        if len(digits) != 2:
            print("   need two bits, like 01")
            continue
        a = int(digits[0])
        b = int(digits[1])
        state, text, bit = apply(a, b)
        expected = 0 if (a and b) else 1
        note = "" if bit == expected else "   <- not what NAND should do"
        print("   A=%d B=%d -> Y = %s (expected %d)%s"
              % (a, b, text, expected, note))

except KeyboardInterrupt:
    pass

# Leave the inputs low: the LED stays on, which is the gate's idle state.
gpio_set(IN_A, False)
gpio_set(IN_B, False)
print("bye")
)";
const uint32_t PROJECT_NAND00_MAIN_PY_HASHES[2] = { 0x2EBF9FB3, 0xF896AD16 };
const int PROJECT_NAND00_MAIN_PY_HASH_COUNT = 2;

const char* PROJECT_NAND00_WIRING_YAML = R"===(version: 2
sourceOfTruth: bridges
meta:
  project: nand00
  title: "Logic Gates 101"
  variant: default
  summary: "A 74HC00 NAND gate driven and read back by the Jumperless"
  script: main.py
  needs: ["74HC00 (DIP-14)", "LED", "330"]
parts:
  - name: "U1"
    type: ic
    value: "74HC00"
    footprint: dip14
    row: 35
    pins:
      A1:  {pin: 1,  connect: RP_GPIO_1, class: signal}
      B1:  {pin: 2,  connect: RP_GPIO_2, class: signal}
      Y1:  {pin: 3,  connect: RP_GPIO_3, class: signal}
      A2:  {pin: 4,  connect: GND,       class: signal}
      B2:  {pin: 5,  connect: GND,       class: signal}
      Y2:  {pin: 6,                      class: nc}
      GND: {pin: 7,  connect: GND,       class: gnd}
      Y3:  {pin: 8,                      class: nc}
      A3:  {pin: 9,  connect: GND,       class: signal}
      B3:  {pin: 10, connect: GND,       class: signal}
      Y4:  {pin: 11,                     class: nc}
      A4:  {pin: 12, connect: GND,       class: signal}
      B4:  {pin: 13, connect: GND,       class: signal}
      VCC: {pin: 14, connect: TOP_RAIL,  class: power}
  - name: "LED1"
    type: led
    footprint: sip2
    row: 18
    pins: {A: {pin: 1}, K: {pin: 2, connect: GND}}
  - name: "R1"
    type: resistor
    value: "330"
    footprint: axial2
    row: 15
    pins: {A: {pin: 1, connect: 37}, B: {pin: 2, connect: 18}}
guide:
  title: "Logic Gates 101"
  steps:
    - {do: note, text: "One NAND gate, wired to three GPIOs. Turn=prev/next, click=confirm, hold=exit."}
    - {do: place, part: U1, check: presence, on_fail: warn, text: "74HC00 across the middle gap, pin 1 (the notch end) at row 35."}
    - {do: place, part: LED1, check: vf, min: 1.4, max: 2.6, on_fail: retry, text: "LED: long leg (anode) row 18, short leg row 19."}
    - {do: place, part: R1, check: continuity, text: "330 resistor: rows 15 and 45, straddling the middle gap."}
    - {do: power_on, check: rail_sane, text: "Confirm to power the gate up (3.3V)."}
    - {do: verify, target: 37, check: voltage, min: 2.2, max: 3.6, text: "Both inputs are low, so NAND out must be high - the LED should be lit."}
    - {do: note, text: "Built. Run main.py for the truth table and the type-your-own-inputs mode."}
power:
  topRail: 3.3
)===";
const uint32_t PROJECT_NAND00_WIRING_YAML_HASHES[2] = { 0x8BE41985, 0x30DA945C };
const int PROJECT_NAND00_WIRING_YAML_HASH_COUNT = 2;

#endif // INCLUDE_PROJECT_NAND00

//==============================================================================
// FilesystemStuff.cpp Integration Guide
//==============================================================================
// Copy the following entries into the projectFiles[] array in
// src/remembering/FilesystemStuff.cpp (used by initializeProjects()).
// ProjectFileInfo struct: { path, content, name, knownHashes, hashCount }
//
// initializeProjects() creates the parent directories of each path on
// demand, so a new project needs no directory list anywhere.
//
// #ifdef INCLUDE_PROJECT_555
//         { "/projects/555/README.md", PROJECT_555_README_MD, "555/README.md", PROJECT_555_README_MD_HASHES, PROJECT_555_README_MD_HASH_COUNT },
//         { "/projects/555/main.py", PROJECT_555_MAIN_PY, "555/main.py", PROJECT_555_MAIN_PY_HASHES, PROJECT_555_MAIN_PY_HASH_COUNT },
//         { "/projects/555/wiring.yaml", PROJECT_555_WIRING_YAML, "555/wiring.yaml", PROJECT_555_WIRING_YAML_HASHES, PROJECT_555_WIRING_YAML_HASH_COUNT },
// #endif
// #ifdef INCLUDE_PROJECT_EEPROM
//         { "/projects/eeprom/README.md", PROJECT_EEPROM_README_MD, "eeprom/README.md", PROJECT_EEPROM_README_MD_HASHES, PROJECT_EEPROM_README_MD_HASH_COUNT },
//         { "/projects/eeprom/main.py", PROJECT_EEPROM_MAIN_PY, "eeprom/main.py", PROJECT_EEPROM_MAIN_PY_HASHES, PROJECT_EEPROM_MAIN_PY_HASH_COUNT },
//         { "/projects/eeprom/wiring.yaml", PROJECT_EEPROM_WIRING_YAML, "eeprom/wiring.yaml", PROJECT_EEPROM_WIRING_YAML_HASHES, PROJECT_EEPROM_WIRING_YAML_HASH_COUNT },
// #endif
// #ifdef INCLUDE_PROJECT_I2CSCRN
//         { "/projects/i2cscrn/README.md", PROJECT_I2CSCRN_README_MD, "i2cscrn/README.md", PROJECT_I2CSCRN_README_MD_HASHES, PROJECT_I2CSCRN_README_MD_HASH_COUNT },
//         { "/projects/i2cscrn/main.py", PROJECT_I2CSCRN_MAIN_PY, "i2cscrn/main.py", PROJECT_I2CSCRN_MAIN_PY_HASHES, PROJECT_I2CSCRN_MAIN_PY_HASH_COUNT },
//         { "/projects/i2cscrn/wiring.yaml", PROJECT_I2CSCRN_WIRING_YAML, "i2cscrn/wiring.yaml", PROJECT_I2CSCRN_WIRING_YAML_HASHES, PROJECT_I2CSCRN_WIRING_YAML_HASH_COUNT },
// #endif
// #ifdef INCLUDE_PROJECT_NAND00
//         { "/projects/nand00/README.md", PROJECT_NAND00_README_MD, "nand00/README.md", PROJECT_NAND00_README_MD_HASHES, PROJECT_NAND00_README_MD_HASH_COUNT },
//         { "/projects/nand00/main.py", PROJECT_NAND00_MAIN_PY, "nand00/main.py", PROJECT_NAND00_MAIN_PY_HASHES, PROJECT_NAND00_MAIN_PY_HASH_COUNT },
//         { "/projects/nand00/wiring.yaml", PROJECT_NAND00_WIRING_YAML, "nand00/wiring.yaml", PROJECT_NAND00_WIRING_YAML_HASHES, PROJECT_NAND00_WIRING_YAML_HASH_COUNT },
// #endif
//

#endif // PROJECT_FILES_H