#ifndef PROJECT_FILES_H
#define PROJECT_FILES_H

#include <stdint.h>

//==============================================================================
// Jumperless Projects - Compile-time Configuration
//==============================================================================
// This file is AUTO-GENERATED by scripts/generate_projects.py
// Do not edit manually! Edit the files in scripts/projects/<dir>/ instead.
//
// Consumed by projectFiles[] / initializeProjects() in
// src/remembering/FilesystemStuff.cpp. These are DEFINITIONS (not extern
// declarations), so exactly ONE translation unit may include this header -
// same rule as micropythonExamples.h.
//==============================================================================

// Define which projects to include at compile time
// Comment out any project you don't want provisioned
#define INCLUDE_PROJECT_555
#define INCLUDE_PROJECT_EEPROM
#define INCLUDE_PROJECT_I2CSCRN
#define INCLUDE_PROJECT_NAND00

// Convenience define to disable every project at once
// #define DISABLE_ALL_PROJECTS

#ifdef DISABLE_ALL_PROJECTS
#undef INCLUDE_PROJECT_555
#undef INCLUDE_PROJECT_EEPROM
#undef INCLUDE_PROJECT_I2CSCRN
#undef INCLUDE_PROJECT_NAND00
#endif

//==============================================================================
// Project Files - Embedded Contents
//==============================================================================

//---------- 555 (scripts/projects/555/) ----------
#ifdef INCLUDE_PROJECT_555
const char* PROJECT_555_README_MD = R"(# 555 LED Flasher

An NE555 wired as an astable multivibrator, blinking an LED at about 1.4 Hz.
The Jumperless makes every connection between the parts; you only push the
parts into the breadboard.

## Parts you need

| Part | Value | Package | Rows |
|------|-------|---------|------|
| U1   | NE555 | DIP-8   | pin 1 at row 35, across the middle gap |
| R1   | 10k   | axial   | 10 - 40, straddling the middle gap |
| R2   | 47k   | axial   | 13 - 43, straddling the middle gap |
| C1   | 10uF  | electrolytic | + at 18, - at 19 |
| LED1 | any   | 2-lead  | anode (long leg) 22, cathode 23 |
| R3   | 330   | axial   | 16 - 46, straddling the middle gap |

Top rail is set to 5 V. ADC0 watches OUT (row 37), ADC1 watches the timing
cap (row 7).

## What it does

R1 charges C1 through R1+R2 and discharges it through R2, so

    f = 1.44 / ((R1 + 2*R2) * C1) = 1.44 / (104k * 10uF) = ~1.4 Hz

The LED blinks at that rate, slightly longer on than off: OUT is high for
0.693*(R1+R2)*C1 = 0.395 s and low for 0.693*R2*C1 = 0.326 s, so the duty
cycle is ~54.8%.

`main.py` counts the edges on OUT and prints a line every 3 seconds
(counting whole edges in a 3 s window means the printed frequency lands on
a 1/3 Hz grid - ±0.33 Hz resolution):

    freq: 1.38 Hz   cap: 2.91 V

and mirrors the frequency to the OLED if one is attached. Hold the
clickwheel to stop it.

## Running it

- **Clickwheel:** `Projects` - it is a top-level menu row, before `Apps` - then
  **555**, and walk the guided build. That is what wires the parts up. Run
  `main.py` when it offers at the end.
- **Headless:** `z 555` on the terminal drives the same flow. Add `new` to
  force a fresh run, `load` to reopen the latest one, `run=<N>` for a specific
  one, `noscript` to stop at the wiring.

Launching a project does not borrow a slot any more. It opens
`/projects/555/555_<N>.yaml` - a **run file** - and makes it your active
circuit, exactly as if you had clicked a YAML in the Files browser. Your build
is saved into it at every step, the board comes back to it after a power cycle,
and the next launch offers to reload it or to start run N+1 (the old one stays
on disk). The shipped `wiring.yaml` is a read-only template and is never
written to.

Clicking `wiring.yaml` in the Files browser starts a run the same way. Either
route, **only a guide commit wires a part**: `expandPartsToBridges()` skips any
part still marked `placed: false`, so a run you have not walked through yet has
nothing on the breadboard except whatever its `bridges:` section already held.

## Moving parts around

**Compact vs expanded.** Every two-leg part can sit two ways. **Expanded** puts
it at its own rows and the Jumperless routes its connections through the
crossbar underneath - good while you are building, because each part is easy to
see and to test on its own. **Compact** is how you would breadboard it by hand:
the legs go straight into the rows they connect to - a resistor from a chip's
pin row to the rail goes leg-in-row-7, leg-in-the-rail - and the routed
connections for that part disappear, because the legs themselves make the
contact.

Tap a part's lit footprint with the probe to flip that one part between the
two. **Every part remembers its own setting.** A leg whose endpoint is not a
real hole - `GND` and the analog pins live in the crossbar, not on the board -
keeps its own row and its routed connection either way, so a compact part can
still have one bridge.

To **move** a part, tap any free hole and pin 1 jumps there. The wheel never
moves a part - it only browses the steps. On the terminal, `m <row>` and `c` do
the same two things the probe does. Chips (DIPs) sit with pin 1 - the dot or the notch - on the **bottom
half** of the board, rows 31-60. Axial parts (resistors, diodes) straddle the
middle gap by default; radial parts (caps, LEDs) sit in two neighbouring rows.

**Browsing.** The wheel moves *between* steps rather than confirming them, and
the ring wraps: turn past the last step and you land on a summary of what is
built, skipped and still outstanding; turn again and you are back at step 1. A
turn never ends the build - hold the wheel, or press `q`, for that. You can skip
a part with `s` and come back to it later, and confirming at the summary jumps
you to the first thing you have not built yet.

> Measuring and *identifying* an unknown part (`identify_part(leftmost_row=...)`)
> is planned but is not in this release. What the guide shows today is the value
> each verify step measures - a resistance, a diode drop, a rail voltage.

## Troubleshooting

- No blink at all: check the 555's orientation - pin 1 (next to the dot) at
  row 35, and the chip must straddle the middle gap.
- Blinking way too fast or slow: R1/R2 swapped, or the cap is not 10uF.
- LED dark but OUT reads ~2.5 V average: the LED is backwards. Long leg goes
  in row 22.
)";
const uint32_t PROJECT_555_README_MD_HASHES[5] = { 0x561E244A, 0x7F9D3D88, 0xE846A64A, 0x52517D68, 0x4E203A59 };
const int PROJECT_555_README_MD_HASH_COUNT = 5;

const char* PROJECT_555_MAIN_PY = R"("""555 LED Flasher - companion script for /projects/555/wiring.yaml

Watches the 555's OUT pin (bridged to ADC0 by the wiring file), counts the
rising edges past a 2.5 V threshold, and reports the blink rate every 3
seconds along with the timing cap's voltage (ADC1 -> node 7).

Runs standalone from the Files browser too - the launcher injects
_jl_project, but nothing here depends on it.
"""

import time

# The launcher injects this global; default so the script also runs standalone.
_jl_project = globals().get("_jl_project", {})

THRESHOLD = 2.5     # volts - the 555's OUT swings rail to rail
REPORT_MS = 3000    # print a line this often

print("555 astable running...")
print("Hold the clickwheel to exit.")
if _jl_project:
    print("project: " + str(_jl_project.get("dir", "555")) +
          "  variant: " + str(_jl_project.get("variant", "default")))

try:
    oled_connect()
except Exception:
    pass

edges = 0
above = adc_get(0) > THRESHOLD
window_start = time.ticks_ms()

try:
    while True:
        out_v = adc_get(0)
        if out_v > THRESHOLD:
            if not above:
                edges += 1     # rising edge
                above = True
        elif out_v < THRESHOLD:
            above = False

        elapsed = time.ticks_diff(time.ticks_ms(), window_start)
        if elapsed >= REPORT_MS:
            freq = (edges * 1000.0) / elapsed
            cap_v = adc_get(1)
            print("freq: %.2f Hz   cap: %.2f V" % (freq, cap_v))
            try:
                oled_print("%.2f Hz" % freq)
            except Exception:
                pass
            edges = 0
            window_start = time.ticks_ms()

        time.sleep(0.002)   # ~500 Hz sampling: plenty for a ~1.4 Hz blink

except KeyboardInterrupt:
    try:
        oled_clear()
    except Exception:
        pass
    print("bye")
)";
const uint32_t PROJECT_555_MAIN_PY_HASHES[2] = { 0x89075267, 0xD488958C };
const int PROJECT_555_MAIN_PY_HASH_COUNT = 2;

const char* PROJECT_555_WIRING_YAML = R"===(version: 2
sourceOfTruth: bridges
meta:
  project: 555
  title: "555 LED Flasher"
  variant: default
  summary: "NE555 astable blinking an LED at ~1.4 Hz"
  script: main.py
  needs: ["NE555 (DIP-8)", "10k", "47k", "10uF cap", "LED", "330"]
parts:
  - name: "U1"
    type: ic
    value: "NE555"
    footprint: dip8
    row: 35
    pins:
      GND:   {pin: 1, connect: GND,      class: gnd}
      TRIG:  {pin: 2, connect: 7,        class: signal}
      OUT:   {pin: 3,                    class: signal}
      RESET: {pin: 4, connect: TOP_RAIL, class: power}
      CTRL:  {pin: 5,                    class: nc}
      THR:   {pin: 6,                    class: signal}
      DIS:   {pin: 7,                    class: signal}
      VCC:   {pin: 8, connect: TOP_RAIL, class: power}
  - name: "R1"
    type: resistor
    value: "10k"
    footprint: axial2
    row: 10
    pins: {A: {pin: 1, connect: TOP_RAIL}, B: {pin: 2, connect: 6}}
  - name: "R2"
    type: resistor
    value: "47k"
    footprint: axial2
    row: 13
    pins: {A: {pin: 1, connect: 6}, B: {pin: 2, connect: 7}}
  - name: "C1"
    type: capacitor
    value: "10uF"
    footprint: sip2
    row: 18
    pins: {PLUS: {pin: 1, connect: 7}, MINUS: {pin: 2, connect: GND}}
  - name: "LED1"
    type: led
    footprint: sip2
    row: 22
    pins: {A: {pin: 1}, K: {pin: 2, connect: GND}}
  - name: "R3"
    type: resistor
    value: "330"
    footprint: axial2
    row: 16
    pins: {A: {pin: 1, connect: 37}, B: {pin: 2, connect: 22}}
guide:
  title: "555 LED Flasher"
  steps:
    - {do: note, text: "A 555 blinker. Wheel: turn=prev/next, click=confirm, hold=exit."}
    - {do: place, part: U1, check: presence, on_fail: warn, text: "555 across the middle gap, pin 1 (the dot) at row 35."}
    - {do: place, part: R1, check: continuity, text: "10k resistor: rows 10 and 40, straddling the middle gap."}
    - {do: place, part: R2, check: continuity, text: "47k resistor: rows 13 and 43, straddling the middle gap."}
    - {do: place, part: C1, check: presence, text: "10uF cap: + (long leg) row 18, - row 19."}
    - {do: place, part: LED1, check: vf, min: 1.4, max: 2.6, on_fail: retry, text: "LED: long leg (anode) row 22, short leg row 23."}
    - {do: place, part: R3, check: continuity, text: "330 resistor: rows 16 and 46, straddling the middle gap."}
    - {do: power_on, check: rail_sane, text: "Confirm to power up (5V)."}
    - {do: verify, target: 37, check: oscillates, min: 0.3, max: 30, text: "The LED should be blinking (~1.4 Hz). Checking OUT..."}
bridges:
  - {n1: ADC0, n2: 37}
  - {n1: ADC1, n2: 7}
nets:
  - {num: 7, name: "TIMING", color: 0xff8800, nodes: [7], user: true}
power:
  topRail: 5.0
)===";
const uint32_t PROJECT_555_WIRING_YAML_HASHES[3] = { 0xEEC03F56, 0x2E55BF41, 0xC8CBC62E };
const int PROJECT_555_WIRING_YAML_HASH_COUNT = 3;

#endif // INCLUDE_PROJECT_555

//---------- eeprom (scripts/projects/eeprom/) ----------
#ifdef INCLUDE_PROJECT_EEPROM
const char* PROJECT_EEPROM_README_MD = R"(# EEPROM Dumper

A 24Cxx serial EEPROM in the breadboard, read over I2C and hex-dumped to the
terminal. The Jumperless makes every connection - including the one that
decides whether the chip can be written at all.

## Parts you need

| Part | Value | Package | Rows |
|------|-------|---------|------|
| U1   | 24C02 (or 24C16) | DIP-8 | pin 1 at row 35, across the middle gap |
| R1   | 4.7k  | axial   | 12 - 42, straddling the middle gap (SDA pull-up) |
| R2   | 4.7k  | axial   | 15 - 45, straddling the middle gap (SCL pull-up) |

Top rail is set to 3.3 V.

The 24Cxx pinout, and where each pin lands with pin 1 at row 35:

| Pin | Name | Row | Goes to |
|---|---|---|---|
| 1 | A0  | 35 | GND |
| 2 | A1  | 36 | GND |
| 3 | A2  | 37 | GND |
| 4 | GND | 38 | GND |
| 5 | SDA | 8  | `RP_GPIO_7` (RP pin 26) |
| 6 | SCL | 7  | `RP_GPIO_8` (RP pin 27) |
| 7 | WP  | 6  | top rail - **write protected** |
| 8 | VCC | 5  | top rail |

A0-A2 all grounded puts the chip at **0x50**.

> **Jumperless V5 only.** This project routes breadboard rows to
> `RP_GPIO_7` and `RP_GPIO_8`, and those nodes exist only on the V5. The original
> Jumperless has exactly three routable GPIO (`RP_GPIO_0` plus UART
> TX/RX), so the wiring loads there but cannot be routed.

### Why the two resistors are not optional

I2C is an open-drain bus: the chips only ever pull the lines *down*, so
something has to pull them back up. A 4-pin display module has pull-ups
soldered on it; a bare DIP EEPROM does not. The RP2350's internal pull-ups
are around 50-80k, and 60k into the crossbar-plus-breadboard capacitance
gives a rise time of a couple of microseconds - well past the 1 us the
100 kHz I2C spec allows. 4.7k brings that down to well under 500 ns.

### Write protect is a wire, not a jumper

Pin 7 (WP) high means "reads only". The wiring holds row 6 at the top
rail, so the chip is genuinely read-only from the moment it powers up -
not read-only by convention.

The optional write test in `main.py` is the only thing that changes that,
and it does so by re-routing, not by asking you to move a jumper:

    disconnect(6, TOP_RAIL)
    connect(6, GND)            # writes enabled for exactly one byte
    ...
    disconnect(6, GND)
    connect(6, TOP_RAIL)       # in a finally, so it always goes back

That re-route runs `refreshConnections()`, which re-asserts the slot's GPIO
configuration onto RP pins 26/27 - so the script rebuilds its `machine.I2C`
object afterwards. If you ever see the restore step report a failure,
re-load the wiring before trusting the chip again.

## What it does

    EEPROM Dumper eeprom
    i2c devices: ['0x50']
    0000  FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF  |................|
    ...
    00F0  FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF  |................|
    256 bytes read.  (all 0xFF - an erased chip)
    dump more - total size in bytes (blank = no):

16 bytes to a line with a printable-ASCII gutter, the same shape `hexdump -C`
uses. Then it offers to read further (for a 24C16, answer `2048`), and last
of all offers the write test, which defaults to **no**.

`ADDR_BITS = 8` at the top of `main.py` covers the 24C01 through 24C16. A
24C32 or larger uses a 16-bit word address - set it to 16 for those.

## Running it

- **Clickwheel:** `Projects` - it is a top-level menu row, before `Apps` - then
  **eeprom**, and walk the guided build. That is what wires the parts up. Run
  `main.py` when it offers at the end.
- **Headless:** `z eeprom` on the terminal drives the same flow. Add `new` to
  force a fresh run, `load` to reopen the latest one, `run=<N>` for a specific
  one, `noscript` to stop at the wiring.

Launching a project does not borrow a slot any more. It opens
`/projects/eeprom/eeprom_<N>.yaml` - a **run file** - and makes it your active
circuit, exactly as if you had clicked a YAML in the Files browser. Your build
is saved into it at every step, the board comes back to it after a power cycle,
and the next launch offers to reload it or to start run N+1 (the old one stays
on disk). The shipped `wiring.yaml` is a read-only template and is never
written to.

Clicking `wiring.yaml` in the Files browser starts a run the same way. Either
route, **only a guide commit wires a part**: `expandPartsToBridges()` skips any
part still marked `placed: false`, so a run you have not walked through yet has
nothing on the breadboard except whatever its `bridges:` section already held.

## Moving parts around

**Compact vs expanded.** Every two-leg part can sit two ways. **Expanded** puts
it at its own rows and the Jumperless routes its connections through the
crossbar underneath - good while you are building, because each part is easy to
see and to test on its own. **Compact** is how you would breadboard it by hand:
the legs go straight into the rows they connect to - a resistor from a chip's
pin row to the rail goes leg-in-row-7, leg-in-the-rail - and the routed
connections for that part disappear, because the legs themselves make the
contact.

Tap a part's lit footprint with the probe to flip that one part between the
two. **Every part remembers its own setting.** A leg whose endpoint is not a
real hole - `GND` and the analog pins live in the crossbar, not on the board -
keeps its own row and its routed connection either way, so a compact part can
still have one bridge.

To **move** a part, tap any free hole and pin 1 jumps there. The wheel never
moves a part - it only browses the steps. On the terminal, `m <row>` and `c` do
the same two things the probe does. Chips (DIPs) sit with pin 1 - the dot or the notch - on the **bottom
half** of the board, rows 31-60. Axial parts (resistors, diodes) straddle the
middle gap by default; radial parts (caps, LEDs) sit in two neighbouring rows.

**Browsing.** The wheel moves *between* steps rather than confirming them, and
the ring wraps: turn past the last step and you land on a summary of what is
built, skipped and still outstanding; turn again and you are back at step 1. A
turn never ends the build - hold the wheel, or press `q`, for that. You can skip
a part with `s` and come back to it later, and confirming at the summary jumps
you to the first thing you have not built yet.

> Measuring and *identifying* an unknown part (`identify_part(leftmost_row=...)`)
> is planned but is not in this release. What the guide shows today is the value
> each verify step measures - a resistance, a diode drop, a rail voltage.

## Troubleshooting

- **`i2c devices: []`** - nothing acked. Most often the chip is in
  backwards: pin 1 is the end with the dot, at row 35, and the chip must
  straddle the middle gap. After that, check that both 4.7k resistors are
  really straddling the gap at rows 12/42 and 15/45.
- **A device answers, but not at 0x50** - one of A0/A1/A2 is not reaching
  GND, which shifts the address. 0x51 means A0 is high, 0x52 means A1, and
  so on. Change `ADDR` in `main.py` to match, or re-seat the chip.
- **The dump repeats every 256 bytes** - that is a 24C02, which really is
  256 bytes; the address wraps.
- **Reads work but the write test says the byte did not stick** - WP did not
  reach GND. Watch the terminal for the restore line; if the re-route
  failed, the chip stayed protected, which is the safe way to fail.
- **The Jumperless's own top OLED misbehaves while this runs** - in its
  default `connection_type 0` it lives on GPIO 7/8, the same pins, and it
  shares the i2c1 peripheral in every mode. Turn it off while you use this
  project.
)";
const uint32_t PROJECT_EEPROM_README_MD_HASHES[6] = { 0x69A73992, 0x97332DFC, 0xAF82DCE7, 0x965FF7AE, 0x35314190, 0xF2E7D49B };
const int PROJECT_EEPROM_README_MD_HASH_COUNT = 6;

const char* PROJECT_EEPROM_MAIN_PY = R"===("""EEPROM Dumper - companion for /projects/eeprom/wiring.yaml.

SDA row -> RP_GPIO_7 (RP pin 26), SCL row -> RP_GPIO_8 (RP pin 27), so
machine.I2C(1) reaches the chip. WP (row 6) sits on the top rail, so the
chip is read-only until the write test re-routes that row. See README.md.
"""

import time

_jl_project = globals().get("_jl_project", {})

SDA_PIN = 26        # node RP_GPIO_7 - the wiring routes row 8 here
SCL_PIN = 27        # node RP_GPIO_8 - the wiring routes row 7 here
I2C_BUS = 1         # 26/27 are i2c1; machine.I2C(0, ...) rejects them
I2C_HZ = 100000
ADDR = 0x50         # A0/A1/A2 grounded by the wiring
ADDR_BITS = 8       # 24C01..24C16; 24C32 and larger need 16
WP_ROW = 6          # 24Cxx pin 7 = write protect, held high
FIRST = 256         # bytes in the opening dump
TEST_AT = 0xFF      # the one address the write test touches


def open_bus():
    """An I2C object, or None with an explanation printed."""
    try:
        import machine
    except Exception as e:
        print("no machine module: " + str(e))
        return None
    # Claim the pins, or every refreshConnections() re-asserts the slot
    # config's pulls onto GPIO 26/27 underneath the I2C peripheral.
    for n in (GPIO_7, GPIO_8):
        try:
            gpio_claim_pin(n)
        except Exception:
            pass
    try:
        return machine.I2C(I2C_BUS, scl=SCL_PIN, sda=SDA_PIN, freq=I2C_HZ)
    except Exception as e:
        print("no I2C on %d/%d: %s" % (SDA_PIN, SCL_PIN, str(e)))
        return None


def release_bus():
    """Give the two pins back. Called on EVERY exit from main(), including
    the one where open_bus() claimed them and then failed to build the I2C
    object - that path used to return past the finally and leak the claim."""
    for n in (GPIO_7, GPIO_8):
        try:
            gpio_release_pin(n)
        except Exception:
            pass


def hexdump(data, base=0):
    for off in range(0, len(data), 16):
        c = data[off:off + 16]
        print("%04X  %-47s  |%s|"
              % (base + off, " ".join("%02X" % b for b in c),
                 "".join(chr(b) if 32 <= b < 127 else "." for b in c)))


def read_block(i2c, start, count):
    """Sequential read, 32 bytes at a time to keep buffers small."""
    out = bytearray()
    while count > 0:
        n = 32 if count > 32 else count
        out += i2c.readfrom_mem(ADDR, start, n, addrsize=ADDR_BITS)
        start += n
        count -= n
    return out


def ask(p):
    try:
        return input(p).strip()
    except EOFError:
        return ""


def write_test(i2c, original):
    """One byte written, read back, put back. Returns the live bus."""
    probe = 0xA5 if original != 0xA5 else 0x5A
    moved = False
    try:
        disconnect(WP_ROW, TOP_RAIL)
        # Never add GND while the rail is still on that row: the two together
        # are a short across the supply, through the crossbar. If the
        # disconnect did not take, stop here - protected is the safe way out.
        if is_connected(WP_ROW, TOP_RAIL):
            print("WP row %d is still on the top rail - refusing to add GND "
                  "(that would short the rail). Write test aborted." % WP_ROW)
            return i2c
        connect(WP_ROW, GND)
        moved = True
        time.sleep(0.05)
        i2c = open_bus()      # the re-route's refresh re-muxed 26/27
        if i2c is None:
            raise OSError("bus gone after the WP re-route")
        i2c.writeto_mem(ADDR, TEST_AT, bytes((probe,)), addrsize=ADDR_BITS)
        time.sleep(0.01)      # 24Cxx write cycle: 5 ms worst case
        back = i2c.readfrom_mem(ADDR, TEST_AT, 1, addrsize=ADDR_BITS)[0]
        print("wrote 0x%02X, read 0x%02X back - %s"
              % (probe, back, "writes work" if back == probe else "no stick"))
        i2c.writeto_mem(ADDR, TEST_AT, bytes((original,)), addrsize=ADDR_BITS)
        time.sleep(0.01)
        print("restored 0x%02X at 0x%02X." % (original, TEST_AT))
    except Exception as e:
        print("write test failed: " + str(e))
    finally:
        if moved:
            try:
                disconnect(WP_ROW, GND)
                connect(WP_ROW, TOP_RAIL)
                time.sleep(0.05)
                i2c = open_bus()
                print("write protect restored (row %d on the rail)." % WP_ROW)
            except Exception as e:
                print("COULD NOT RESTORE WRITE PROTECT: " + str(e))
                print("re-load the wiring before trusting the chip.")
    return i2c


def main():
    print("EEPROM Dumper " + str(_jl_project.get("dir", "")))
    i2c = open_bus()
    try:
        if i2c is None:
            return                  # inside the try: the finally still runs
        found = i2c.scan()
        print("i2c devices: " + str([hex(a) for a in found]))
        if ADDR not in found:
            print("no chip at " + hex(ADDR) + " - check the rail, the "
                  "pull-ups (rows 12/42 and 15/45) and A0-A2 to GND.")
            return
        data = read_block(i2c, 0x00, FIRST)
        hexdump(data, 0)
        blank = True
        for b in data:
            if b != 0xFF:
                blank = False
                break
        print("%d bytes read." % len(data) +
              ("  (all 0xFF - an erased chip)" if blank else ""))
        try:
            oled_print("EE %d B" % len(data))
        except Exception:
            pass
        more = ask("dump more - total size in bytes (blank = no): ")
        if more:
            total = int(more) if more.isdigit() else 0
            if total > FIRST:
                if ADDR_BITS == 8 and total > 256:
                    print("note: ADDR_BITS is 8, so past 0xFF wraps.")
                hexdump(read_block(i2c, FIRST, total - FIRST), FIRST)
                print("%d bytes read." % total)
        # WP is a wire the board owns, so read-only is topology here, not
        # convention. Default is no.
        print("Write test: one byte at 0x%02X, read back, original put "
              "back. WP moves to GND only for that." % TEST_AT)
        if ask("run the write test? [y/N] ").lower() == "y":
            i2c = write_test(i2c, data[TEST_AT] if len(data) > TEST_AT else 0xFF)
        else:
            print("skipped - the chip stays read-only.")
    except KeyboardInterrupt:
        print("")
    except Exception as e:
        print("failed: " + str(e))
    finally:
        release_bus()
        print("bye")


main()
)===";
const uint32_t PROJECT_EEPROM_MAIN_PY_HASHES[5] = { 0x1E5C7C14, 0x5E61C1F1, 0x0D73F0A3, 0x70FDD4AE, 0x9B89537B };
const int PROJECT_EEPROM_MAIN_PY_HASH_COUNT = 5;

const char* PROJECT_EEPROM_WIRING_YAML = R"===(version: 2
sourceOfTruth: bridges
meta:
  project: eeprom
  title: "EEPROM Dumper"
  variant: default
  summary: "Hex-dump a 24Cxx I2C EEPROM, with write protect held by the board"
  script: main.py
  needs: ["24C02 or 24C16 (DIP-8)", "4.7k", "4.7k"]
parts:
  - name: "U1"
    type: ic
    value: "24C02"
    footprint: dip8
    row: 35
    pins:
      A0:  {pin: 1, connect: GND,       class: signal}
      A1:  {pin: 2, connect: GND,       class: signal}
      A2:  {pin: 3, connect: GND,       class: signal}
      GND: {pin: 4, connect: GND,       class: gnd}
      SDA: {pin: 5, connect: RP_GPIO_7, class: signal}
      SCL: {pin: 6, connect: RP_GPIO_8, class: signal}
      WP:  {pin: 7, connect: TOP_RAIL,  class: signal}
      VCC: {pin: 8, connect: TOP_RAIL,  class: power}
  - name: "R1"
    type: resistor
    value: "4.7k"
    footprint: axial2
    row: 12
    pins: {A: {pin: 1, connect: TOP_RAIL}, B: {pin: 2, connect: 8}}
  - name: "R2"
    type: resistor
    value: "4.7k"
    footprint: axial2
    row: 15
    pins: {A: {pin: 1, connect: TOP_RAIL}, B: {pin: 2, connect: 7}}
guide:
  title: "EEPROM Dumper"
  steps:
    - {do: note, text: "A 24Cxx EEPROM on the I2C pins. Turn=prev/next, click=confirm, hold=exit."}
    - {do: place, part: U1, check: presence, on_fail: warn, text: "24Cxx across the middle gap, pin 1 (the dot) at row 35."}
    - {do: place, part: R1, check: continuity, text: "4.7k SDA pull-up: rows 12 and 42, straddling the middle gap."}
    - {do: place, part: R2, check: continuity, text: "4.7k SCL pull-up: rows 15 and 45, straddling the middle gap."}
    - {do: power_on, check: rail_sane, text: "Confirm to power the chip up (3.3V). WP is held high - reads only."}
    - {do: verify, target: 8, n1: 8, n2: 7, check: i2c, text: "Scanning the bus - a 24Cxx with A0-A2 grounded answers at 0x50."}
    - {do: note, text: "Built. Run main.py to hex-dump it."}
power:
  topRail: 3.3
config:
  gpio:
    pulls: [0,0,0,0,0,0,1,1,0,0]
)===";
const uint32_t PROJECT_EEPROM_WIRING_YAML_HASHES[2] = { 0x82F38CF1, 0x77CA786A };
const int PROJECT_EEPROM_WIRING_YAML_HASH_COUNT = 2;

#endif // INCLUDE_PROJECT_EEPROM

//---------- i2cscrn (scripts/projects/i2cscrn/) ----------
#ifdef INCLUDE_PROJECT_I2CSCRN
const char* PROJECT_I2CSCRN_README_MD = R"(# Type to Screen

An SSD1306 OLED module pushed into the breadboard, wired to the Jumperless's
I2C pins by the crossbar. You type a line in the terminal, it appears on the
panel. No jumper wires - the Jumperless makes every connection.

## Parts you need

| Part | Package | Rows |
|------|---------|------|
| DISP | SSD1306 I2C module, 4-pin header | 5 - 8 |

The four pins go, in order: **GND at row 5, VCC at row 6, SCL at row 7,
SDA at row 8**. That is the pin order printed on nearly every cheap 0.96"
and 0.91" module, but *check your silkscreen before powering up* - a few
boards swap VCC and GND, and that is the one mistake that kills the panel.

Top rail is set to 3.3 V. Rows 7 and 8 are routed to `RP_GPIO_8` (RP pin 27,
SCL) and `RP_GPIO_7` (RP pin 26, SDA) - the same pair the built-in I2C
scanner uses.

> **Jumperless V5 only.** This project routes breadboard rows to
> `RP_GPIO_7` and `RP_GPIO_8`, and those nodes exist only on the V5. The original
> Jumperless has exactly three routable GPIO (`RP_GPIO_0` plus UART
> TX/RX), so the wiring loads there but cannot be routed.

## What it does

`main.py` opens `machine.I2C(1, scl=27, sda=26)`, scans the bus, and then
loops on `input()`. Each line you type is pushed onto a short history and
redrawn on the panel:

    Type to Screen
    i2c devices: ['0x3c']
    panel up: 128x32, 4 rows of 16 chars
    Type a line and press enter. Empty line clears. 'q' quits.
    > hello jumperless

An empty line clears the screen, `q` quits, and Ctrl-C works too.

The driver is deliberately tiny: MicroPython's `framebuf` module supplies
the pixel buffer and the built-in 8x8 font, and the `Screen` class in
`main.py` only adds the SSD1306 command set on top (init sequence, column
and page window, the `0x40` data prefix).

`HEIGHT = 32` at the top of `main.py` is the one thing to change for a
128x64 panel - set it to 64 and the driver picks the right multiplex ratio
and COM pin configuration by itself.

## Running it

- **Clickwheel:** `Projects` - it is a top-level menu row, before `Apps` - then
  **i2cscrn**, and walk the guided build. That is what wires the parts up. Run
  `main.py` when it offers at the end.
- **Headless:** `z i2cscrn` on the terminal drives the same flow. Add `new` to
  force a fresh run, `load` to reopen the latest one, `run=<N>` for a specific
  one, `noscript` to stop at the wiring.

Launching a project does not borrow a slot any more. It opens
`/projects/i2cscrn/i2cscrn_<N>.yaml` - a **run file** - and makes it your active
circuit, exactly as if you had clicked a YAML in the Files browser. Your build
is saved into it at every step, the board comes back to it after a power cycle,
and the next launch offers to reload it or to start run N+1 (the old one stays
on disk). The shipped `wiring.yaml` is a read-only template and is never
written to.

Clicking `wiring.yaml` in the Files browser starts a run the same way. Either
route, **only a guide commit wires a part**: `expandPartsToBridges()` skips any
part still marked `placed: false`, so a run you have not walked through yet has
nothing on the breadboard except whatever its `bridges:` section already held.

## Moving parts around

**Compact vs expanded.** Every two-leg part can sit two ways. **Expanded** puts
it at its own rows and the Jumperless routes its connections through the
crossbar underneath - good while you are building, because each part is easy to
see and to test on its own. **Compact** is how you would breadboard it by hand:
the legs go straight into the rows they connect to - a resistor from a chip's
pin row to the rail goes leg-in-row-7, leg-in-the-rail - and the routed
connections for that part disappear, because the legs themselves make the
contact.

Tap a part's lit footprint with the probe to flip that one part between the
two. **Every part remembers its own setting.** A leg whose endpoint is not a
real hole - `GND` and the analog pins live in the crossbar, not on the board -
keeps its own row and its routed connection either way, so a compact part can
still have one bridge.

To **move** a part, tap any free hole and pin 1 jumps there. The wheel never
moves a part - it only browses the steps. On the terminal, `m <row>` and `c` do
the same two things the probe does. Chips (DIPs) sit with pin 1 - the dot or the notch - on the **bottom
half** of the board, rows 31-60. Axial parts (resistors, diodes) straddle the
middle gap by default; radial parts (caps, LEDs) sit in two neighbouring rows.

**Browsing.** The wheel moves *between* steps rather than confirming them, and
the ring wraps: turn past the last step and you land on a summary of what is
built, skipped and still outstanding; turn again and you are back at step 1. A
turn never ends the build - hold the wheel, or press `q`, for that. You can skip
a part with `s` and come back to it later, and confirming at the summary jumps
you to the first thing you have not built yet.

> Measuring and *identifying* an unknown part (`identify_part(leftmost_row=...)`)
> is planned but is not in this release. What the guide shows today is the value
> each verify step measures - a resistance, a diode drop, a rail voltage.

## Troubleshooting

- **`i2c devices: []`** - nothing acked. Check that the module is really in
  rows 5-8 with GND at 5, that the top rail is at 3.3 V, and that SCL/SDA
  are not swapped (row 7 is SCL, row 8 is SDA).
- **A device answers, but at some other address** - most 128x64 boards can
  be strapped to 0x3D. Change `ADDR` at the top of `main.py`.
- **Bare panel, no breakout board** - the 4-pin modules carry their own
  pull-up resistors. A raw panel does not; add 4.7k from row 7 and from
  row 8 up to the top rail (that is exactly what the `eeprom` project
  does for its bare chip).
- **The Jumperless's own top OLED behaves oddly while this runs** - in its
  default `connection_type 0` it lives on GPIO 7/8, the very pins this
  project uses, and it shares the i2c1 peripheral in every mode. Turn it
  off (or move it to the hardwired pins) while you play with this project.
- **The screen shows garbage after a while** - drop `I2C_HZ` to 50000.
  Long crossbar paths plus breadboard capacitance slow the edges down.
)";
const uint32_t PROJECT_I2CSCRN_README_MD_HASHES[4] = { 0xF62F698B, 0x9006DDCB, 0x4A5A7256, 0xBFC48EF5 };
const int PROJECT_I2CSCRN_README_MD_HASH_COUNT = 4;

const char* PROJECT_I2CSCRN_MAIN_PY = R"("""Type to Screen - companion for /projects/i2cscrn/wiring.yaml.

SCL row -> RP_GPIO_8 (RP pin 27), SDA row -> RP_GPIO_7 (RP pin 26), so
machine.I2C(1) reaches the panel. framebuf owns the pixels and the 8x8
font; Screen only adds the SSD1306 command set. See README.md.
"""

_jl_project = globals().get("_jl_project", {})

SDA_PIN = 26        # node RP_GPIO_7 - wiring.yaml routes row 8 here
SCL_PIN = 27        # node RP_GPIO_8 - wiring.yaml routes row 7 here
I2C_BUS = 1         # 26/27 are i2c1; machine.I2C(0, ...) rejects them
I2C_HZ = 100000     # the scanner's rate - kind to breadboard capacitance
ADDR = 0x3C         # 0x3D on a few 128x64 boards
WIDTH = 128
HEIGHT = 32         # <- set to 64 for a 128x64 panel


class Screen:
    def __init__(self, i2c, addr, width, height):
        import framebuf
        self.i2c = i2c
        self.addr = addr
        self.width = width
        self.pages = height // 8
        self.buf = bytearray(self.pages * width)
        self.fb = framebuf.FrameBuffer(self.buf, width, height,
                                       framebuf.MONO_VLSB)
        self.tx = bytearray(1 + len(self.buf))
        self.tx[0] = 0x40             # "data follows"
        self.rows = self.pages        # 8 px per text row
        self.cols = width // 8        # 8 px per character
        # off, clkdiv, mux, offset, startline, pump, horiz mode, seg remap,
        # com scan dec, com pins, contrast, precharge, vcomh, RAM, normal, on
        for c in (0xAE, 0xD5, 0x80, 0xA8, height - 1, 0xD3, 0x00, 0x40,
                  0x8D, 0x14, 0x20, 0x00, 0xA1, 0xC8,
                  0xDA, 0x02 if height == 32 else 0x12,
                  0x81, 0xCF, 0xD9, 0xF1, 0xDB, 0x40, 0xA4, 0xA6, 0xAF):
            self.cmd(c)

    def cmd(self, c):
        self.i2c.writeto(self.addr, bytes((0x00, c)))   # 0x00 = command

    def show(self):
        self.cmd(0x21); self.cmd(0); self.cmd(self.width - 1)   # columns
        self.cmd(0x22); self.cmd(0); self.cmd(self.pages - 1)   # pages
        self.tx[1:] = self.buf
        self.i2c.writeto(self.addr, self.tx)

    def lines(self, texts):
        self.fb.fill(0)
        y = 0
        for t in texts:
            self.fb.text(t[:self.cols], 0, y, 1)
            y += 8
        self.show()


def open_bus():
    """An I2C object, or None with an explanation printed."""
    try:
        import machine
    except Exception as e:
        print("no machine module: " + str(e))
        return None
    # Claim the pins, or every refreshConnections() re-asserts the slot
    # config's pulls onto GPIO 26/27 underneath the I2C peripheral.
    for n in (GPIO_7, GPIO_8):
        try:
            gpio_claim_pin(n)
        except Exception:
            pass
    try:
        return machine.I2C(I2C_BUS, scl=SCL_PIN, sda=SDA_PIN, freq=I2C_HZ)
    except Exception as e:
        print("no I2C on %d/%d: %s" % (SDA_PIN, SCL_PIN, str(e)))
        return None


print("Type to Screen")
if _jl_project:
    print("project: " + str(_jl_project.get("dir", "i2cscrn")))

scr = None
i2c = open_bus()
if i2c is not None:
    found = i2c.scan()
    print("i2c devices: " + str([hex(a) for a in found]))
    if ADDR not in found:
        print("no panel at " + hex(ADDR) + " - check power, the SDA/SCL "
              "order, and the address jumper")
    else:
        try:
            scr = Screen(i2c, ADDR, WIDTH, HEIGHT)
            scr.lines(["Type to Screen", "ready."])
            print("panel up: %dx%d, %d rows of %d chars"
                  % (WIDTH, HEIGHT, scr.rows, scr.cols))
        except Exception as e:
            print("panel init failed: " + str(e))
if scr is None:
    print("terminal-only mode - fix the wiring and re-run.")
print("Type a line and press enter. Empty line clears. 'q' quits.")

history = []
try:
    while True:
        try:
            typed = input("> ")
        except EOFError:
            break
        if typed == "q":
            break
        if typed == "":
            history = []
        else:
            history.append(typed)
            history = history[-(scr.rows if scr else 4):]
        if scr is None:
            print("screen: " + str(history))
        else:
            try:
                scr.lines(history)
            except Exception as e:
                print("write failed: " + str(e))
except KeyboardInterrupt:
    pass

if scr is not None:
    try:
        scr.lines([])
    except Exception:
        pass
for n in (GPIO_7, GPIO_8):
    try:
        gpio_release_pin(n)
    except Exception:
        pass
print("bye")
)";
const uint32_t PROJECT_I2CSCRN_MAIN_PY_HASHES[2] = { 0xDC3D3F52, 0x79C8D0B3 };
const int PROJECT_I2CSCRN_MAIN_PY_HASH_COUNT = 2;

const char* PROJECT_I2CSCRN_WIRING_YAML = R"===(version: 2
sourceOfTruth: bridges
meta:
  project: i2cscrn
  title: "Type to Screen"
  variant: default
  summary: "An SSD1306 on the breadboard, echoing whatever you type"
  script: main.py
  needs: ["SSD1306 I2C module (4-pin: GND VCC SCL SDA)"]
parts:
  - name: "DISP"
    type: ic
    value: "SSD1306"
    footprint: sip4
    row: 5
    pins:
      GND: {pin: 1, connect: GND,       class: gnd}
      VCC: {pin: 2, connect: TOP_RAIL,  class: power}
      SCL: {pin: 3, connect: RP_GPIO_8, class: signal}
      SDA: {pin: 4, connect: RP_GPIO_7, class: signal}
guide:
  title: "Type to Screen"
  steps:
    - {do: note, text: "An SSD1306 the Jumperless talks to. Turn=prev/next, click=confirm, hold=exit."}
    - {do: place, part: DISP, check: presence, on_fail: warn, text: "Header in rows 5-8: GND 5, VCC 6, SCL 7, SDA 8. Check the silkscreen order."}
    - {do: power_on, check: rail_sane, text: "Confirm to power the display (3.3V on the top rail)."}
    - {do: verify, target: 8, n1: 8, n2: 7, check: i2c, text: "Scanning the bus - the panel should answer (0x3C on nearly every module)."}
    - {do: note, text: "Wired. Run main.py and type a line - it lands on the screen."}
power:
  topRail: 3.3
config:
  gpio:
    pulls: [0,0,0,0,0,0,1,1,0,0]
)===";
const uint32_t PROJECT_I2CSCRN_WIRING_YAML_HASHES[1] = { 0xBEE331D0 };
const int PROJECT_I2CSCRN_WIRING_YAML_HASH_COUNT = 1;

#endif // INCLUDE_PROJECT_I2CSCRN

//---------- nand00 (scripts/projects/nand00/) ----------
#ifdef INCLUDE_PROJECT_NAND00
const char* PROJECT_NAND00_README_MD = R"(# Logic Gates 101

A 74HC00 quad NAND gate. The Jumperless drives both inputs of gate 1, reads
its output back, and lights an LED from the same output - so you can watch
the truth table and measure it at the same time.

## Parts you need

| Part | Value | Package | Rows |
|------|-------|---------|------|
| U1   | 74HC00 | DIP-14 | pin 1 at row 35, across the middle gap |
| LED1 | any   | 2-lead  | anode (long leg) 18, cathode 19 |
| R1   | 330   | axial   | 15 - 45, straddling the middle gap |

Top rail is set to **3.3 V**, not 5 V: rows 35, 36 and 37 land on real RP2350
pins, and those are 3.3 V parts. A 74HC00 is perfectly happy anywhere from
2 V to 6 V.

Pin map for gate 1:

| 74HC00 pin | Row | Goes to |
|---|---|---|
| 1 (1A) | 35 | `RP_GPIO_1` - the Jumperless drives it |
| 2 (1B) | 36 | `RP_GPIO_2` - the Jumperless drives it |
| 3 (1Y) | 37 | `RP_GPIO_3` for readback, and R1 -> LED1 -> GND |
| 7 (GND) | 41 | GND |
| 14 (VCC) | 5 | top rail |

> **Jumperless V5 only.** This project routes breadboard rows to
> `RP_GPIO_1`, `RP_GPIO_2` and `RP_GPIO_3`, and those nodes exist only on the V5. The original
> Jumperless has exactly three routable GPIO (`RP_GPIO_0` plus UART
> TX/RX), so the wiring loads there but cannot be routed.

The other three gates are not used, so their inputs (pins 4, 5, 9, 10, 12,
13) are tied to GND. That is not decoration: a floating CMOS input drifts
around its switching threshold, oscillates, and makes the chip draw far more
current than it should.

## What it does

      A  B  | Y  expected  LED
      ------+-----------------
      0  0  | 1  1         on    ok
      0  1  | 1  1         on    ok
      1  0  | 1  1         on    ok
      1  1  | 0  0         off   ok

    All four rows match NAND. That is a working gate.

NAND is "not and": the output is high unless **both** inputs are high. So
the LED is lit for three of the four input combinations and dark for the
fourth.

After the table, `main.py` drops into a live mode. Type `10` and the board
sets A high, B low, and reads the result back:

    A B> 10
       A=1 B=0 -> Y = HIGH (expected 1)

`q` quits, and Ctrl-C works too.

## Running it

- **Clickwheel:** `Projects` - it is a top-level menu row, before `Apps` - then
  **nand00**, and walk the guided build. That is what wires the parts up. Run
  `main.py` when it offers at the end.
- **Headless:** `z nand00` on the terminal drives the same flow. Add `new` to
  force a fresh run, `load` to reopen the latest one, `run=<N>` for a specific
  one, `noscript` to stop at the wiring.

Launching a project does not borrow a slot any more. It opens
`/projects/nand00/nand00_<N>.yaml` - a **run file** - and makes it your active
circuit, exactly as if you had clicked a YAML in the Files browser. Your build
is saved into it at every step, the board comes back to it after a power cycle,
and the next launch offers to reload it or to start run N+1 (the old one stays
on disk). The shipped `wiring.yaml` is a read-only template and is never
written to.

Clicking `wiring.yaml` in the Files browser starts a run the same way. Either
route, **only a guide commit wires a part**: `expandPartsToBridges()` skips any
part still marked `placed: false`, so a run you have not walked through yet has
nothing on the breadboard except whatever its `bridges:` section already held.

## Moving parts around

**Compact vs expanded.** Every two-leg part can sit two ways. **Expanded** puts
it at its own rows and the Jumperless routes its connections through the
crossbar underneath - good while you are building, because each part is easy to
see and to test on its own. **Compact** is how you would breadboard it by hand:
the legs go straight into the rows they connect to - a resistor from a chip's
pin row to the rail goes leg-in-row-7, leg-in-the-rail - and the routed
connections for that part disappear, because the legs themselves make the
contact.

Tap a part's lit footprint with the probe to flip that one part between the
two. **Every part remembers its own setting.** A leg whose endpoint is not a
real hole - `GND` and the analog pins live in the crossbar, not on the board -
keeps its own row and its routed connection either way, so a compact part can
still have one bridge.

To **move** a part, tap any free hole and pin 1 jumps there. The wheel never
moves a part - it only browses the steps. On the terminal, `m <row>` and `c` do
the same two things the probe does. Chips (DIPs) sit with pin 1 - the dot or the notch - on the **bottom
half** of the board, rows 31-60. Axial parts (resistors, diodes) straddle the
middle gap by default; radial parts (caps, LEDs) sit in two neighbouring rows.

**Browsing.** The wheel moves *between* steps rather than confirming them, and
the ring wraps: turn past the last step and you land on a summary of what is
built, skipped and still outstanding; turn again and you are back at step 1. A
turn never ends the build - hold the wheel, or press `q`, for that. You can skip
a part with `s` and come back to it later, and confirming at the summary jumps
you to the first thing you have not built yet.

> Measuring and *identifying* an unknown part (`identify_part(leftmost_row=...)`)
> is planned but is not in this release. What the guide shows today is the value
> each verify step measures - a resistance, a diode drop, a rail voltage.

## Troubleshooting

- **Every read says `FLOATING`** - the output pin is not driving. Check that
  the chip straddles the middle gap with pin 1 (next to the notch) at row 35,
  and that the top rail really is at 3.3 V.
- **The LED never lights but the readback is right** - the LED is backwards.
  The long leg goes in row 18.
- **The LED is on for all four rows** - the output is stuck high. Most often
  input pin 1 or 2 is not seated: a floating HC input drifts high, and two
  high inputs are the only case NAND pulls low.
- **The LED is on for exactly one row, `1 1`** - that is a 74HC**08** (AND).
  AND is NAND's exact inverse, so it lights the one row NAND darkens. Check
  the part number on the chip.
- **A 74HC02 (NOR) is worse than wrong here.** Its pin 1 is an *output*
  (1Y), not an input, and this wiring drives pin 1 from `RP_GPIO_1` - two
  drivers fighting over one node. Pull it out rather than leaving it
  powered, and use a 74HC00.
- **The last two rows disagree** - one of the two input legs (rows 35, 36) is
  not making contact.
)";
const uint32_t PROJECT_NAND00_README_MD_HASHES[5] = { 0x94003C75, 0x59A4BE23, 0x36273393, 0x6F684328, 0x66A8E629 };
const int PROJECT_NAND00_README_MD_HASH_COUNT = 5;

const char* PROJECT_NAND00_MAIN_PY = R"("""Logic Gates 101 - companion script for /projects/nand00/wiring.yaml

Gate 1 of a 74HC00 is wired so the Jumperless owns all three of its pins:
GPIO_1 -> pin 1 (A), GPIO_2 -> pin 2 (B), pin 3 (Y) -> GPIO_3 and the LED.
So the board can drive the inputs, read the output back, and check the chip
against the truth table it is supposed to obey.

Runs standalone from the Files browser too - the launcher injects
_jl_project, but nothing here depends on it.
"""

import time

# The launcher injects this global; default so the script also runs standalone.
_jl_project = globals().get("_jl_project", {})

IN_A = GPIO_1       # node 131 -> row 35 -> 74HC00 pin 1
IN_B = GPIO_2       # node 132 -> row 36 -> 74HC00 pin 2
OUT = GPIO_3        # node 133 -> row 37 -> 74HC00 pin 3

SETTLE_S = 0.02     # the gate switches in nanoseconds; this is for the LED


def setup():
    gpio_set_dir(IN_A, True)      # True = OUTPUT
    gpio_set_dir(IN_B, True)
    gpio_set_dir(OUT, False)      # False = INPUT
    gpio_set_pull(OUT, 0)         # no pull - the 74HC00 drives this line
    gpio_set(IN_A, False)
    gpio_set(IN_B, False)


def read_out():
    """(state_object, text, bit_or_None). bit is None when the line floats."""
    s = gpio_get(OUT)
    t = str(s)
    if s == 1:
        return s, t, 1
    if s == 0:
        return s, t, 0
    return s, t, None


def apply(a, b):
    gpio_set(IN_A, bool(a))
    gpio_set(IN_B, bool(b))
    time.sleep(SETTLE_S)
    return read_out()


print("Logic Gates 101 - 74HC00 NAND")
if _jl_project:
    print("project: " + str(_jl_project.get("dir", "nand00")) +
          "  variant: " + str(_jl_project.get("variant", "default")))

setup()

print("")
print("  A  B  | Y  expected  LED")
print("  ------+-----------------")

wrong = 0
floated = 0
for a, b in ((0, 0), (0, 1), (1, 0), (1, 1)):
    state, text, bit = apply(a, b)
    expected = 0 if (a and b) else 1
    if bit is None:
        floated += 1
        verdict = "FLOATING"
    elif bit != expected:
        wrong += 1
        verdict = "WRONG"
    else:
        verdict = "ok"
    print("  %d  %d  | %s  %d         %s   %s"
          % (a, b, ("1" if bit == 1 else "0" if bit == 0 else "?"),
             expected, "on " if expected else "off", verdict))

print("")
if floated:
    print("%d of 4 reads floated - is the 74HC00 seated, and is the rail on?"
          % floated)
elif wrong:
    print("%d of 4 rows disagree with NAND - wrong chip, or a leg not in "
          "its hole?" % wrong)
else:
    print("All four rows match NAND. That is a working gate.")

try:
    oled_print("NAND ok" if (not wrong and not floated) else "NAND ??")
except Exception:
    pass

print("")
print("Live mode: type two bits (00, 01, 10, 11) to set the inputs.")
print("Empty line re-reads without changing anything. 'q' quits.")

try:
    while True:
        try:
            typed = input("A B> ").strip()
        except EOFError:
            break
        if typed == "q":
            break
        if typed == "":
            state, text, bit = read_out()
            print("   Y = " + text)
            continue
        digits = [c for c in typed if c in "01"]
        if len(digits) != 2:
            print("   need two bits, like 01")
            continue
        a = int(digits[0])
        b = int(digits[1])
        state, text, bit = apply(a, b)
        expected = 0 if (a and b) else 1
        note = "" if bit == expected else "   <- not what NAND should do"
        print("   A=%d B=%d -> Y = %s (expected %d)%s"
              % (a, b, text, expected, note))

except KeyboardInterrupt:
    pass

# Leave the inputs low: the LED stays on, which is the gate's idle state.
gpio_set(IN_A, False)
gpio_set(IN_B, False)
print("bye")
)";
const uint32_t PROJECT_NAND00_MAIN_PY_HASHES[2] = { 0x2EBF9FB3, 0xF896AD16 };
const int PROJECT_NAND00_MAIN_PY_HASH_COUNT = 2;

const char* PROJECT_NAND00_WIRING_YAML = R"===(version: 2
sourceOfTruth: bridges
meta:
  project: nand00
  title: "Logic Gates 101"
  variant: default
  summary: "A 74HC00 NAND gate driven and read back by the Jumperless"
  script: main.py
  needs: ["74HC00 (DIP-14)", "LED", "330"]
parts:
  - name: "U1"
    type: ic
    value: "74HC00"
    footprint: dip14
    row: 35
    pins:
      A1:  {pin: 1,  connect: RP_GPIO_1, class: signal}
      B1:  {pin: 2,  connect: RP_GPIO_2, class: signal}
      Y1:  {pin: 3,  connect: RP_GPIO_3, class: signal}
      A2:  {pin: 4,  connect: GND,       class: signal}
      B2:  {pin: 5,  connect: GND,       class: signal}
      Y2:  {pin: 6,                      class: nc}
      GND: {pin: 7,  connect: GND,       class: gnd}
      Y3:  {pin: 8,                      class: nc}
      A3:  {pin: 9,  connect: GND,       class: signal}
      B3:  {pin: 10, connect: GND,       class: signal}
      Y4:  {pin: 11,                     class: nc}
      A4:  {pin: 12, connect: GND,       class: signal}
      B4:  {pin: 13, connect: GND,       class: signal}
      VCC: {pin: 14, connect: TOP_RAIL,  class: power}
  - name: "LED1"
    type: led
    footprint: sip2
    row: 18
    pins: {A: {pin: 1}, K: {pin: 2, connect: GND}}
  - name: "R1"
    type: resistor
    value: "330"
    footprint: axial2
    row: 15
    pins: {A: {pin: 1, connect: 37}, B: {pin: 2, connect: 18}}
guide:
  title: "Logic Gates 101"
  steps:
    - {do: note, text: "One NAND gate, wired to three GPIOs. Turn=prev/next, click=confirm, hold=exit."}
    - {do: place, part: U1, check: presence, on_fail: warn, text: "74HC00 across the middle gap, pin 1 (the notch end) at row 35."}
    - {do: place, part: LED1, check: vf, min: 1.4, max: 2.6, on_fail: retry, text: "LED: long leg (anode) row 18, short leg row 19."}
    - {do: place, part: R1, check: continuity, text: "330 resistor: rows 15 and 45, straddling the middle gap."}
    - {do: power_on, check: rail_sane, text: "Confirm to power the gate up (3.3V)."}
    - {do: verify, target: 37, check: voltage, min: 2.2, max: 3.6, text: "Both inputs are low, so NAND out must be high - the LED should be lit."}
    - {do: note, text: "Built. Run main.py for the truth table and the type-your-own-inputs mode."}
power:
  topRail: 3.3
)===";
const uint32_t PROJECT_NAND00_WIRING_YAML_HASHES[2] = { 0x8BE41985, 0x30DA945C };
const int PROJECT_NAND00_WIRING_YAML_HASH_COUNT = 2;

#endif // INCLUDE_PROJECT_NAND00

//==============================================================================
// FilesystemStuff.cpp Integration Guide
//==============================================================================
// Copy the following entries into the projectFiles[] array in
// src/remembering/FilesystemStuff.cpp (used by initializeProjects()).
// ProjectFileInfo struct: { path, content, name, knownHashes, hashCount }
//
// initializeProjects() creates the parent directories of each path on
// demand, so a new project needs no directory list anywhere.
//
// #ifdef INCLUDE_PROJECT_555
//         { "/projects/555/README.md", PROJECT_555_README_MD, "555/README.md", PROJECT_555_README_MD_HASHES, PROJECT_555_README_MD_HASH_COUNT },
//         { "/projects/555/main.py", PROJECT_555_MAIN_PY, "555/main.py", PROJECT_555_MAIN_PY_HASHES, PROJECT_555_MAIN_PY_HASH_COUNT },
//         { "/projects/555/wiring.yaml", PROJECT_555_WIRING_YAML, "555/wiring.yaml", PROJECT_555_WIRING_YAML_HASHES, PROJECT_555_WIRING_YAML_HASH_COUNT },
// #endif
// #ifdef INCLUDE_PROJECT_EEPROM
//         { "/projects/eeprom/README.md", PROJECT_EEPROM_README_MD, "eeprom/README.md", PROJECT_EEPROM_README_MD_HASHES, PROJECT_EEPROM_README_MD_HASH_COUNT },
//         { "/projects/eeprom/main.py", PROJECT_EEPROM_MAIN_PY, "eeprom/main.py", PROJECT_EEPROM_MAIN_PY_HASHES, PROJECT_EEPROM_MAIN_PY_HASH_COUNT },
//         { "/projects/eeprom/wiring.yaml", PROJECT_EEPROM_WIRING_YAML, "eeprom/wiring.yaml", PROJECT_EEPROM_WIRING_YAML_HASHES, PROJECT_EEPROM_WIRING_YAML_HASH_COUNT },
// #endif
// #ifdef INCLUDE_PROJECT_I2CSCRN
//         { "/projects/i2cscrn/README.md", PROJECT_I2CSCRN_README_MD, "i2cscrn/README.md", PROJECT_I2CSCRN_README_MD_HASHES, PROJECT_I2CSCRN_README_MD_HASH_COUNT },
//         { "/projects/i2cscrn/main.py", PROJECT_I2CSCRN_MAIN_PY, "i2cscrn/main.py", PROJECT_I2CSCRN_MAIN_PY_HASHES, PROJECT_I2CSCRN_MAIN_PY_HASH_COUNT },
//         { "/projects/i2cscrn/wiring.yaml", PROJECT_I2CSCRN_WIRING_YAML, "i2cscrn/wiring.yaml", PROJECT_I2CSCRN_WIRING_YAML_HASHES, PROJECT_I2CSCRN_WIRING_YAML_HASH_COUNT },
// #endif
// #ifdef INCLUDE_PROJECT_NAND00
//         { "/projects/nand00/README.md", PROJECT_NAND00_README_MD, "nand00/README.md", PROJECT_NAND00_README_MD_HASHES, PROJECT_NAND00_README_MD_HASH_COUNT },
//         { "/projects/nand00/main.py", PROJECT_NAND00_MAIN_PY, "nand00/main.py", PROJECT_NAND00_MAIN_PY_HASHES, PROJECT_NAND00_MAIN_PY_HASH_COUNT },
//         { "/projects/nand00/wiring.yaml", PROJECT_NAND00_WIRING_YAML, "nand00/wiring.yaml", PROJECT_NAND00_WIRING_YAML_HASHES, PROJECT_NAND00_WIRING_YAML_HASH_COUNT },
// #endif
//

#endif // PROJECT_FILES_H