// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// --------------- //
// encoder_sampler //
// --------------- //

#define encoder_sampler_wrap_target 0
#define encoder_sampler_wrap 0
#define encoder_sampler_pio_version 0

static const uint16_t encoder_sampler_program_instructions[] = {
            //     .wrap_target
    0x4002, //  0: in     pins, 2
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program encoder_sampler_program = {
    .instructions = encoder_sampler_program_instructions,
    .length = 1,
    .origin = -1,
    .pio_version = encoder_sampler_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config encoder_sampler_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + encoder_sampler_wrap_target, offset + encoder_sampler_wrap);
    return c;
}

#include "hardware/clocks.h"
#include "hardware/gpio.h"
static inline void encoder_sampler_program_init(PIO pio, uint sm, uint offset, uint pin, float sample_hz) {
    pio_sm_set_consecutive_pindirs(pio, sm, pin, 2, false);
    // The pins keep their existing config (pulled-up GPIO inputs; the E9
    // pad-IE mitigation twiddles them every 5 ms) - a PIO 'in' needs no
    // funcsel, so no pio_gpio_init here. The pulls are (re)asserted so this
    // init stays self-sufficient for the day the legacy program - whose init
    // owned them - is removed.
    gpio_pull_up(pin);
    gpio_pull_up(pin + 1);
    pio_sm_config c = encoder_sampler_program_get_default_config(offset);
    sm_config_set_in_pins(&c, pin);
    // shift left (oldest sample at the MSB end), autopush every 32 bits
    sm_config_set_in_shift(&c, false, true, 32);
    sm_config_set_fifo_join(&c, PIO_FIFO_JOIN_RX);
    // one instruction per loop: the clock divider IS the sample rate
    sm_config_set_clkdiv(&c, (float)clock_get_hz(clk_sys) / sample_hz);
    pio_sm_init(pio, sm, offset, &c);
    pio_sm_clear_fifos(pio, sm);
    pio_sm_set_enabled(pio, sm, true);
}

#endif

