#!/usr/bin/env python3
"""
Generate src/snakes/projectFiles.h from the scripts/projects/<dir>/ trees.

Companion to generate_micropython_examples.py: same mechanism (raw C string
literals + FNV-1a content hashes + an accumulating hash history), applied to
whole project directories instead of a flat folder of .py examples.

Every text file under scripts/projects/<dir>/ becomes an embedded constant
PROJECT_<DIR>_<FILE>; FilesystemStuff.cpp's projectFiles[] table points at
those constants and initializeProjects() writes them to /projects/<dir>/<file>
on the board (see CodeDocs/DESIGN_PROJECTS_SUBSYSTEM.md section 1,
"Provisioning + generator + flash budget").

Workflow for adding a project:
  1. mkdir scripts/projects/<dir>/  (dir name <= 7 chars - the LED matrix
     click-menu view renders it as a 7-char row) and put wiring.yaml /
     main.py / README.md in it.
  2. python3 scripts/generate_projects.py
  3. Paste the printed table fragment (also at the bottom of the generated
     header) into projectFiles[] in src/remembering/FilesystemStuff.cpp.
  4. Rebuild; commit the header AND scripts/projects_hash_history.json.

The output is deterministic: running the generator twice with no source change
produces a byte-identical header and history file.
"""

import sys
from pathlib import Path

SCRIPT_DIR = Path(__file__).parent
if str(SCRIPT_DIR) not in sys.path:
    sys.path.insert(0, str(SCRIPT_DIR))

# Shared with the examples generator - one implementation of the C string
# escaping and of the FNV-1a that must match the firmware's fnv1a32_file().
from generate_micropython_examples import (  # noqa: E402
    fnv1a32,
    hashes_to_c_array,
    load_hash_history,
    py_to_c_string,
    save_hash_history,
    update_history,
)

# Only text files get embedded. Anything else in a project dir (compiled
# .pyc, images, editor backups) is ignored rather than silently mangled.
TEXT_EXTENSIONS = {".yaml", ".yml", ".py", ".md", ".txt"}

# Directories never walked into.
SKIP_DIRS = {"__pycache__", ".git", ".vscode"}


def sanitize(text: str) -> str:
    """Uppercase C-identifier fragment: everything but [A-Za-z0-9] -> '_'."""
    return "".join(c if c.isalnum() else "_" for c in text).upper()


def dir_to_define_name(dir_name: str) -> str:
    """555 -> INCLUDE_PROJECT_555 (one gate per project, not per file:
    half a project on the filesystem is a broken project)."""
    return f"INCLUDE_PROJECT_{sanitize(dir_name)}"


def file_to_var_name(dir_name: str, rel_path: str) -> str:
    """(555, wiring.yaml) -> PROJECT_555_WIRING_YAML"""
    return f"PROJECT_{sanitize(dir_name)}_{sanitize(rel_path)}"


def collect_project_files(project_dir: Path) -> list:
    """Sorted list of embeddable files in a project dir, as POSIX-relative
    path strings. Recurses, so a project may carry a subdirectory."""
    found = []
    for path in sorted(project_dir.rglob("*")):
        if not path.is_file():
            continue
        if any(part in SKIP_DIRS or part.startswith(".") for part in
               path.relative_to(project_dir).parts):
            continue
        if path.suffix.lower() not in TEXT_EXTENSIONS:
            continue
        found.append(path.relative_to(project_dir).as_posix())
    return found


def collect_projects(projects_root: Path) -> list:
    """[(dir_name, [rel_path, ...]), ...], alphabetical, empty dirs dropped."""
    projects = []
    for entry in sorted(projects_root.iterdir()):
        if not entry.is_dir():
            continue
        if entry.name in SKIP_DIRS or entry.name.startswith("."):
            continue
        files = collect_project_files(entry)
        if not files:
            print(f"  (skipping {entry.name}/ - no embeddable text files)")
            continue
        projects.append((entry.name, files))
    return projects


def generate_header(projects_root: Path, output_file: Path,
                    history_path: Path) -> int:
    history = load_hash_history(history_path)
    projects = collect_projects(projects_root)

    lines = [
        "#ifndef PROJECT_FILES_H",
        "#define PROJECT_FILES_H",
        "",
        "#include <stdint.h>",
        "",
        "//==============================================================================",
        "// Jumperless Projects - Compile-time Configuration",
        "//==============================================================================",
        "// This file is AUTO-GENERATED by scripts/generate_projects.py",
        "// Do not edit manually! Edit the files in scripts/projects/<dir>/ instead.",
        "//",
        "// Consumed by projectFiles[] / initializeProjects() in",
        "// src/remembering/FilesystemStuff.cpp. These are DEFINITIONS (not extern",
        "// declarations), so exactly ONE translation unit may include this header -",
        "// same rule as micropythonExamples.h.",
        "//==============================================================================",
        "",
        "// Define which projects to include at compile time",
        "// Comment out any project you don't want provisioned",
    ]

    for dir_name, _ in projects:
        lines.append(f"#define {dir_to_define_name(dir_name)}")

    lines.extend([
        "",
        "// Convenience define to disable every project at once",
        "// #define DISABLE_ALL_PROJECTS",
        "",
        "#ifdef DISABLE_ALL_PROJECTS",
    ])
    for dir_name, _ in projects:
        lines.append(f"#undef {dir_to_define_name(dir_name)}")
    lines.extend([
        "#endif",
        "",
        "//==============================================================================",
        "// Project Files - Embedded Contents",
        "//==============================================================================",
        "",
    ])

    total_files = 0
    total_bytes = 0

    for dir_name, files in projects:
        define_name = dir_to_define_name(dir_name)
        lines.extend([
            f"//---------- {dir_name} (scripts/projects/{dir_name}/) ----------",
            f"#ifdef {define_name}",
        ])

        for rel_path in files:
            source = projects_root / dir_name / rel_path
            print(f"Processing {dir_name}/{rel_path}...")

            with open(source, "r", encoding="utf-8") as f:
                content = f.read()

            var_name = file_to_var_name(dir_name, rel_path)
            c_string = py_to_c_string(content)
            content_hash = fnv1a32(content.encode("utf-8"))

            # History is keyed by "<dir>/<file>", NOT by bare filename: every
            # project carries a wiring.yaml/main.py/README.md, so bare names
            # would collide across projects and cross-contaminate the
            # user-edit detection.
            all_hashes = update_history(history, f"{dir_name}/{rel_path}",
                                        content_hash)
            hash_count = len(all_hashes)

            lines.extend([
                f"const char* {var_name} = {c_string};",
                f"const uint32_t {var_name}_HASHES[{hash_count}] = "
                f"{{ {hashes_to_c_array(all_hashes)} }};",
                f"const int {var_name}_HASH_COUNT = {hash_count};",
                "",
            ])

            total_files += 1
            total_bytes += len(content.encode("utf-8"))

        lines.extend([
            f"#endif // {define_name}",
            "",
        ])

    # Ready-to-paste table fragment (mirrors the examples header's
    # "Integration Guide" section).
    lines.extend([
        "//==============================================================================",
        "// FilesystemStuff.cpp Integration Guide",
        "//==============================================================================",
        "// Copy the following entries into the projectFiles[] array in",
        "// src/remembering/FilesystemStuff.cpp (used by initializeProjects()).",
        "// ProjectFileInfo struct: { path, content, name, knownHashes, hashCount }",
        "//",
        "// initializeProjects() creates the parent directories of each path on",
        "// demand, so a new project needs no directory list anywhere.",
        "//",
    ])

    fragment = []
    for dir_name, files in projects:
        fragment.append(f"#ifdef {dir_to_define_name(dir_name)}")
        for rel_path in files:
            var_name = file_to_var_name(dir_name, rel_path)
            fragment.append(
                f'        {{ "/projects/{dir_name}/{rel_path}", {var_name}, '
                f'"{dir_name}/{rel_path}", {var_name}_HASHES, '
                f"{var_name}_HASH_COUNT }},")
        fragment.append("#endif")

    for frag_line in fragment:
        lines.append(f"// {frag_line}")
    lines.append("//")

    lines.extend([
        "",
        "#endif // PROJECT_FILES_H",
    ])

    save_hash_history(history_path, history)
    print(f"✓ Updated hash history: {history_path}")

    with open(output_file, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

    print(f"\n✓ Generated {output_file}")
    print(f"✓ Processed {len(projects)} project(s), {total_files} file(s), "
          f"{total_bytes} bytes of embedded content")
    print()
    print("Paste this into projectFiles[] in src/remembering/FilesystemStuff.cpp:")
    print()
    for frag_line in fragment:
        print(frag_line)
    print()
    return total_files


def main():
    project_root = SCRIPT_DIR.parent
    projects_root = project_root / "scripts" / "projects"
    output_header = project_root / "src" / "snakes" / "projectFiles.h"
    history_file = SCRIPT_DIR / "projects_hash_history.json"

    print("=" * 70)
    print("Generating projectFiles.h")
    print("=" * 70)
    print(f"Source directory: {projects_root}")
    print(f"Output file: {output_header}")
    print()

    if not projects_root.exists():
        print(f"ERROR: Source directory not found: {projects_root}")
        sys.exit(1)

    try:
        num_files = generate_header(projects_root, output_header, history_file)
        print("=" * 70)
        print("SUCCESS!")
        print("=" * 70)
        print(f"Updated {output_header} with {num_files} project file(s)")
    except Exception as e:
        print(f"\nERROR: {e}")
        import traceback
        traceback.print_exc()
        sys.exit(1)


if __name__ == "__main__":
    main()
