// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ------------------ //
// spi_ch446_multi_cs //
// ------------------ //

#define spi_ch446_multi_cs_wrap_target 0
#define spi_ch446_multi_cs_wrap 9
#define spi_ch446_multi_cs_pio_version 0

#define spi_ch446_multi_cs_offset_entry_point 8u

static const uint16_t spi_ch446_multi_cs_program_instructions[] = {
            //     .wrap_target
    0x6201, //  0: out    pins, 1         side 0 [2]
    0xb242, //  1: nop                    side 1 [2]
    0x1040, //  2: jmp    x--, 0          side 1
    0x7001, //  3: out    pins, 1         side 1
    0xb022, //  4: mov    x, y            side 1
    0xd001, //  5: irq    nowait 1        side 1
    0x3051, //  6: wait   0 irq, 1 rel    side 1
    0x00e0, //  7: jmp    !osre, 0        side 0
    0x81e0, //  8: pull   ifempty block   side 0 [1]
    0xa142, //  9: nop                    side 0 [1]
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program spi_ch446_multi_cs_program = {
    .instructions = spi_ch446_multi_cs_program_instructions,
    .length = 10,
    .origin = -1,
    .pio_version = spi_ch446_multi_cs_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config spi_ch446_multi_cs_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + spi_ch446_multi_cs_wrap_target, offset + spi_ch446_multi_cs_wrap);
    sm_config_set_sideset(&c, 1, false, false);
    return c;
}

// The shifter init used by CH446Q.cpp's legacy path (the pio2cs shifter has
// its own init in CH446Q.cpp). Side-set = CK, out pin = DAT; flag 1 routed to
// PIO0_IRQ_1, which initCH446Q() enables on the core that registers isrFromPio.
#include "hardware/gpio.h"
static inline void pio_spi_ch446_multi_cs_init(PIO pio, uint sm, uint prog_offs, uint n_bits, float clkdiv, bool cpha, bool cpol,
                                               uint pin_sck, uint pin_mosi) {
    (void)cpha; (void)cpol;
    pio_sm_config c = spi_ch446_multi_cs_program_get_default_config(prog_offs);
    sm_config_set_out_pins(&c, pin_mosi, 1);
    sm_config_set_set_pins(&c, pin_sck, 1);
    sm_config_set_sideset_pins(&c, pin_sck);
    sm_config_set_out_shift(&c, false, true, n_bits);
    sm_config_set_clkdiv(&c, clkdiv);
    pio_sm_set_consecutive_pindirs(pio, sm, pin_mosi, 2, true);
    gpio_set_drive_strength(pin_sck, GPIO_DRIVE_STRENGTH_12MA);
    gpio_set_drive_strength(pin_mosi, GPIO_DRIVE_STRENGTH_12MA);
    gpio_set_slew_rate(pin_sck, GPIO_SLEW_RATE_FAST);
    gpio_set_slew_rate(pin_mosi, GPIO_SLEW_RATE_FAST);
    pio_gpio_init(pio, pin_mosi);
    pio_gpio_init(pio, pin_sck);
    // The IRQ source is per flag; "1 rel" on state machine 0 is flag 1, and
    // isrFromPio clears flag 1 - so this must be interrupt1 + sm.
    pio_set_irq1_source_enabled(pio, (pio_interrupt_source)(pis_interrupt1 + sm), true);
    pio_interrupt_clear(pio, sm);
    irq_set_enabled(PIO0_IRQ_1, true);
    uint entry_point = prog_offs;
    pio_sm_init(pio, sm, entry_point, &c);
    pio_sm_exec(pio, sm, pio_encode_set(pio_x, n_bits - 2));
    pio_sm_exec(pio, sm, pio_encode_set(pio_y, n_bits - 2));
    pio_sm_set_enabled(pio, sm, true);
}

#endif

