// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ---------------- //
// spi_ch446_pio2cs //
// ---------------- //

#define spi_ch446_pio2cs_wrap_target 0
#define spi_ch446_pio2cs_wrap 9
#define spi_ch446_pio2cs_pio_version 1

#define spi_ch446_pio2cs_offset_entry_point 8u

static const uint16_t spi_ch446_pio2cs_program_instructions[] = {
            //     .wrap_target
    0x6201, //  0: out    pins, 1         side 0 [2]
    0xb242, //  1: nop                    side 1 [2]
    0x1040, //  2: jmp    x--, 0          side 1
    0x7001, //  3: out    pins, 1         side 1
    0xb022, //  4: mov    x, y            side 1
    0xd00c, //  5: irq    prev nowait 4   side 1
    0x30c5, //  6: wait   1 irq, 5        side 1
    0x00e0, //  7: jmp    !osre, 0        side 0
    0x81e0, //  8: pull   ifempty block   side 0 [1]
    0xa142, //  9: nop                    side 0 [1]
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program spi_ch446_pio2cs_program = {
    .instructions = spi_ch446_pio2cs_program_instructions,
    .length = 10,
    .origin = -1,
    .pio_version = spi_ch446_pio2cs_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config spi_ch446_pio2cs_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + spi_ch446_pio2cs_wrap_target, offset + spi_ch446_pio2cs_wrap);
    sm_config_set_sideset(&c, 1, false, false);
    return c;
}
#endif

// --------------- //
// ch446_cs_strobe //
// --------------- //

#define ch446_cs_strobe_wrap_target 0
#define ch446_cs_strobe_wrap 7
#define ch446_cs_strobe_pio_version 1

#define ch446_cs_strobe_offset_entry_point 0u

static const uint16_t ch446_cs_strobe_program_instructions[] = {
            //     .wrap_target
    0x80a0, //  0: pull   block
    0x20c4, //  1: wait   1 irq, 4
    0x770c, //  2: out    pins, 12               [23]
    0xa003, //  3: mov    pins, null
    0xc01d, //  4: irq    next nowait 5
    0x6021, //  5: out    x, 1
    0x0020, //  6: jmp    !x, 0
    0xc000, //  7: irq    nowait 0
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program ch446_cs_strobe_program = {
    .instructions = ch446_cs_strobe_program_instructions,
    .length = 8,
    .origin = -1,
    .pio_version = ch446_cs_strobe_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config ch446_cs_strobe_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + ch446_cs_strobe_wrap_target, offset + ch446_cs_strobe_wrap);
    return c;
}
#endif

